const { B } = require('../dsl.js');
const { JOURS, JOURS5 } = require('./commun.js');

const base = { cat: 'acm', theme: 'Accueil de loisirs', metiers: ['animation', 'associatif', 'education'], publics: ['equipes', 'familles'], modele: true };
const REGLE = 'Modèle à adapter : les obligations exactes dépendent du type d’accueil et de la réglementation en vigueur (code de l’action sociale et des familles, services départementaux de la jeunesse). Vérifiez-les avec votre organisateur.';

module.exports = [
  {
    ...base,
    id: 'fiche-d-inscription-accueil-de-loisirs',
    titre: 'Fiche d’inscription en accueil de loisirs',
    description: 'L’enfant, les responsables légaux, les personnes à joindre, les autorisations et les informations utiles : la fiche complète, sur une page.',
    kicker: 'Accueil de loisirs · inscription',
    t1: 'Fiche', t2: 'd’inscription', sous: 'une par enfant',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ titre: 'L’enfant', items: [['Nom et prénom', 1], ['Date de naissance', 1], ['Adresse', 1], ['Classe ou établissement scolaire', 1]], cols: 2, couleur: 'indigo' }),
      B.tableau({ titre: 'Responsables légaux', cols: [{ t: '', w: 22 }, { t: 'Responsable 1', w: 39 }, { t: 'Responsable 2', w: 39 }], lignes: [['Nom et prénom', '', ''], ['Lien avec l’enfant', '', ''], ['Téléphone', '', ''], ['E-mail', '', '']], premiereGras: true, h: 9 }),
      B.cocher('Autorisations (cochez)', ['Mon enfant peut participer aux sorties prévues au programme.', 'Mon enfant peut être photographié (voir l’autorisation de droit à l’image).', 'Mon enfant peut rentrer seul à partir de ____ h.'], { cols: 1 }),
      B.champs({ items: [['Informations utiles (régime alimentaire, habitudes, peurs)', 2]] }),
      B.signatures(['Date et signature du responsable légal']),
      B.texte(REGLE, true),
    ],
  },
  {
    ...base,
    id: 'personnes-autorisees-a-recuperer-l-enfant',
    titre: 'Personnes autorisées à récupérer l’enfant',
    description: 'Qui peut venir chercher l’enfant, avec quel lien et quel téléphone, et la règle de la pièce d’identité au premier passage.',
    kicker: 'Accueil de loisirs · départ',
    t1: 'Qui vient', t2: 'me chercher ?', sous: 'personne d’autre sans accord écrit',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Enfant', 1], ['Responsable légal qui remplit', 1]], cols: 2 }),
      B.tableau({ cols: [{ t: 'Nom et prénom', w: 32 }, { t: 'Lien avec l’enfant', w: 22 }, { t: 'Téléphone', w: 22 }, { t: 'Valable jusqu’au', w: 24 }], vides: 6, h: 12 }),
      B.puces('La règle', ['Une personne qui n’est pas sur cette liste ne repart pas avec l’enfant sans accord écrit du responsable légal.', 'L’équipe peut demander une pièce d’identité, surtout la première fois.', 'Le responsable légal prévient l’équipe de tout changement.'], 'corail'),
      B.signatures(['Date et signature du responsable légal']),
    ],
  },
  {
    ...base,
    id: 'fiche-de-renseignements-sanitaires',
    titre: 'Fiche de renseignements sanitaires',
    description: 'Vaccinations, allergies, traitement, régime, médecin traitant et personne à prévenir : la fiche santé à joindre à l’inscription, à garder confidentielle.',
    publics: ['familles', 'equipes'],
    kicker: 'Accueil de loisirs · santé',
    t1: 'Renseignements', t2: 'sanitaires', sous: 'confidentiel, réservé à l’équipe',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Enfant, date de naissance', 1], ['Responsable légal et téléphone', 1], ['Médecin traitant et téléphone', 1], ['Personne à prévenir en cas d’urgence', 1]], cols: 2 }),
      B.champs({ titre: 'Vaccinations', items: [['Joindre la copie des pages vaccinations du carnet de santé, ou une attestation du médecin', 1]] }),
      B.cote(B.champs({ titre: 'Allergies', items: [['Alimentaires, médicamenteuses, autres, et conduite à tenir', 3]], couleur: 'corail' }), B.champs({ titre: 'Traitement en cours', items: [['Joindre l’ordonnance et les médicaments dans leur boîte', 3]] })),
      B.champs({ items: [['Projet d’accueil individualisé (PAI) : oui / non', 1], ['Régime alimentaire', 1], ['Autres informations utiles (lunettes, appareil, peurs, sommeil)', 2]], cols: 1 }),
      B.texte('J’autorise le responsable de l’accueil à prendre, le cas échéant, toutes les mesures rendues nécessaires par l’état de santé de mon enfant, en lien avec les services de secours.', false),
      B.signatures(['Date et signature du responsable légal']),
      B.texte('Ces informations sont confidentielles : elles ne sont accessibles qu’aux personnes qui en ont besoin pour la sécurité de l’enfant, et sont détruites à la fin de l’accueil. ' + REGLE, true),
    ],
  },
  {
    ...base,
    id: 'registre-des-soins',
    titre: 'Registre des soins (cahier d’infirmerie)',
    description: 'Date, heure, enfant, ce qui s’est passé, le soin donné, qui l’a donné et si la famille a été prévenue : le registre à tenir chaque jour.',
    kicker: 'Accueil de loisirs · santé',
    t1: 'Registre', t2: 'des soins', sous: 'chaque soin, même petit',
    format: 'Registre A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.tableau({ feuille: 'Soins', cols: [{ t: 'Date, heure', w: 11 }, { t: 'Enfant', w: 14 }, { t: 'Ce qui s’est passé', w: 24 }, { t: 'Soin donné', w: 20 }, { t: 'Par', w: 11 }, { t: 'Famille prévenue (heure)', w: 11 }, { t: 'Signature', w: 9 }], vides: 10, h: 9 }),
      B.texte('On n’administre un médicament que sur ordonnance et avec l’accord écrit des responsables légaux. En cas de doute, on appelle le 15. ' + REGLE, true),
    ],
  },
  {
    ...base,
    id: 'inventaire-de-la-trousse-de-premiers-soins',
    titre: 'Inventaire de la trousse de premiers soins',
    description: 'Le contenu à vérifier avant chaque sortie, avec la quantité et la date de péremption, et la case du contrôle.',
    kicker: 'Accueil de loisirs · sécurité',
    t1: 'Ma trousse', t2: 'de premiers soins', sous: 'vérifiée avant chaque sortie',
    format: 'Check-list A4 · 1 page', mod: ['docx', 'xlsx'],
    corps: [
      B.tableau({ feuille: 'Trousse', cols: [{ t: 'Élément', w: 40 }, { t: 'Quantité', w: 14 }, { t: 'Péremption', w: 16 }, { t: 'Vérifié le', w: 15 }, { t: 'Par', w: 15 }], lignes: ['Compresses stériles', 'Pansements de tailles variées', 'Bande de gaze et sparadrap', 'Solution de lavage (sérum physiologique en dosettes)', 'Antiseptique sans alcool', 'Ciseaux à bouts ronds', 'Pince à échardes', 'Gants jetables', 'Couverture de survie', 'Poche de froid instantané', 'Sacs pour déchets', 'Fiche des numéros d’urgence', 'Fiches des enfants (allergies, PAI) et traitements prévus'].map((x) => [x, '', '', '', '']), h: 9 }),
      B.texte('La composition de la trousse est à valider avec le référent santé de votre structure. Les médicaments n’y entrent que sur ordonnance, au nom de l’enfant.', true),
    ],
  },
  {
    ...base,
    id: 'feuille-de-pointage-groupe-en-deplacement',
    titre: 'Feuille de pointage du groupe en déplacement',
    description: 'Les enfants du groupe, un adulte référent par sous-groupe, et une colonne par point de comptage : départ, transport, arrivée, retour.',
    kicker: 'Sortie · comptage',
    t1: 'Pointage', t2: 'du groupe', sous: 'on compte à chaque étape',
    format: 'Feuille A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true, modele: false,
    corps: [
      B.champs({ items: [['Sortie', 1], ['Date', 1], ['Responsable', 1], ['Nombre d’enfants au départ', 1]], cols: 2 }),
      B.tableau({ feuille: 'Pointage', cols: [{ t: 'Enfant', w: 22 }, { t: 'Adulte référent', w: 16 }, { t: 'Départ', w: 10 }, { t: 'Montée transport', w: 10 }, { t: 'Arrivée', w: 10 }, { t: 'Repas', w: 10 }, { t: 'Retour transport', w: 11 }, { t: 'Arrivée structure', w: 11 }], vides: 10, h: 8 }),
    ],
  },
  {
    ...base,
    id: 'menu-de-la-semaine',
    titre: 'Menu de la semaine à afficher',
    description: 'Entrée, plat, accompagnement, dessert et goûter pour cinq jours, avec la ligne des allergènes à signaler aux familles.',
    publics: ['familles', 'equipes', 'enfants'],
    metiers: ['animation', 'associatif', 'education', 'protection', 'handicap'],
    kicker: 'Repas · familles',
    t1: 'Le menu', t2: 'de la semaine', sous: 'à afficher à l’entrée',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true, modele: false,
    corps: [
      B.champs({ items: [['Semaine du … au …', 1]] }),
      B.tableau({ feuille: 'Menu', cols: [{ t: '', w: 15 }, ...JOURS5.map((j) => ({ t: j, w: 17 }))], lignes: ['Entrée', 'Plat', 'Accompagnement', 'Dessert', 'Goûter', 'Allergènes'].map((m) => [m, '', '', '', '', '']), premiereGras: true, h: 14 }),
      B.texte('Les quatorze allergènes à déclarer : gluten, crustacés, œufs, poissons, arachides, soja, lait, fruits à coque, céleri, moutarde, sésame, sulfites, lupin, mollusques.', true),
    ],
  },
  {
    ...base,
    id: 'plan-de-couchage-sejour',
    titre: 'Plan de couchage d’un séjour',
    description: 'Les chambres, les enfants dans chacune, l’animateur de proximité et les besoins de nuit (veilleuse, doudou, réveil) : à afficher pour l’équipe.',
    publics: ['equipes'],
    kicker: 'Séjour · nuit',
    t1: 'Plan', t2: 'de couchage', sous: 'qui dort où, qui veille',
    format: 'Tableau A4 · 1 page', mod: ['xlsx', 'docx'],
    corps: [
      B.champs({ items: [['Séjour et lieu', 1], ['Dates', 1]], cols: 2 }),
      B.tableau({ feuille: 'Couchage', cols: [{ t: 'Chambre', w: 14 }, { t: 'Enfants', w: 40 }, { t: 'Animateur de proximité', w: 22 }, { t: 'Besoins de nuit', w: 24 }], vides: 10, h: 16 }),
      B.texte('Filles et garçons dorment dans des chambres séparées à partir de l’âge fixé par la réglementation de votre accueil. Les enfants de moins de six ans ont des conditions propres : vérifiez-les. ' + REGLE, true),
    ],
  },
  {
    ...base,
    id: 'trame-projet-pedagogique-accueil-de-loisirs',
    titre: 'Trame de projet pédagogique d’accueil de loisirs',
    description: 'Les rubriques d’un projet pédagogique : le public, les objectifs, la journée type, les règles de vie, le rôle de chacun, l’évaluation.',
    publics: ['equipes'],
    kicker: 'Accueil de loisirs · projet',
    t1: 'Projet', t2: 'pédagogique', sous: 'écrit avec l’équipe',
    format: 'Trame A4 · 2 pages', mod: ['docx'],
    pages: [
      [
        B.champs({ titre: '1. L’accueil', items: [['Organisateur, lieu, période, capacité', 2], ['Le public : âges, nombre, besoins particuliers', 2]], couleur: 'indigo' }),
        B.champs({ titre: '2. Le lien avec le projet éducatif', items: [['Les intentions de l’organisateur que ce projet met en œuvre', 3]] }),
        B.tableau({ titre: '3. Objectifs pédagogiques', cols: [{ t: 'Objectif', w: 34 }, { t: 'Comment on y travaille', w: 36 }, { t: 'Comment on saura', w: 30 }], vides: 4, h: 16 }),
      ],
      [
        B.tableau({ titre: '4. La journée type', cols: [{ t: 'Horaire', w: 16 }, { t: 'Moment', w: 40 }, { t: 'Rôle de l’équipe', w: 44 }], vides: 7, h: 10 }),
        B.cote(B.champs({ titre: '5. Règles de vie', items: [['', 4]] }), B.champs({ titre: '6. Rôle de chacun', items: [['Direction, animateurs, autres', 4]] })),
        B.champs({ titre: '7. Évaluation', items: [['Quand, avec qui, avec quels outils', 3]], couleur: 'vert' }),
      ],
    ],
    lex: { outil: 'objectifs', libelle: 'Écrire mes objectifs avec LEX' },
  },
  {
    ...base,
    id: 'affiche-le-groupe-est-en-sortie',
    titre: 'Affiche : le groupe est en sortie',
    description: 'L’affiche à laisser sur la porte : où est le groupe, jusqu’à quelle heure, et le téléphone de l’adulte responsable.',
    publics: ['equipes', 'familles'],
    kicker: 'Affiche · sortie',
    t1: 'Le groupe', t2: 'est en sortie', sous: 'nous revenons bientôt',
    format: 'Affiche A4', mod: ['docx'], classe: 'poster', modele: false,
    corps: [
      B.cartes({ items: [['🚌', 'Nous sommes partis à']], cols: 1, h: 40 }),
      B.champs({ items: [['Lieu', 1], ['Retour prévu à', 1], ['Adulte responsable', 1], ['Téléphone', 1]], cols: 1 }),
    ],
  },
  {
    ...base,
    id: 'check-list-depart-minibus',
    titre: 'Check-list départ en minibus',
    description: 'Le conducteur, le véhicule, les sièges et rehausseurs, le comptage, les papiers : les points à vérifier avant de tourner la clé.',
    publics: ['equipes'],
    kicker: 'Transport · minibus',
    t1: 'Avant', t2: 'de démarrer', sous: 'le minibus, point par point',
    format: 'Check-list A4 · 1 page', mod: ['docx'], modele: false,
    corps: [
      B.cote(
        B.cocher('Le conducteur', ['Permis valide pour le véhicule.', 'Autorisé à conduire par la structure.', 'Reposé, sans alcool ni médicament qui gêne la conduite.']),
        B.cocher('Le véhicule', ['Pneus, feux, essuie-glaces.', 'Carburant suffisant pour l’aller-retour.', 'Gilet et triangle, trousse de secours.']),
      ),
      B.cote(
        B.cocher('Les passagers', ['Une place assise et une ceinture par personne.', 'Rehausseurs ou sièges adaptés selon l’âge et la taille.', 'Liste des passagers à bord, comptage fait.']),
        B.cocher('Les papiers', ['Carte grise et attestation d’assurance.', 'Fiche de sortie et téléphone de la structure.', 'Numéros d’urgence.']),
      ),
      B.texte(REGLE, true),
    ],
  },
  {
    ...base,
    id: 'fiche-incident-ou-accident',
    titre: 'Fiche incident ou accident en accueil de loisirs',
    description: 'Ce qui s’est passé, les soins donnés, qui a été prévenu, les témoins et les suites : la fiche à remplir le jour même et à remettre à la direction.',
    publics: ['equipes'],
    kicker: 'Accueil de loisirs · incident',
    t1: 'Fiche', t2: 'incident ou accident', sous: 'le jour même, des faits',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Enfant', 1], ['Date, heure, lieu', 1], ['Activité en cours', 1], ['Rédigé par', 1]], cols: 2 }),
      B.champs({ titre: 'Ce qui s’est passé', items: [['Dans l’ordre, sans interprétation', 4]], couleur: 'indigo' }),
      B.cote(B.champs({ titre: 'Soins donnés', items: [['', 3]] }), B.champs({ titre: 'Personnes prévenues', items: [['Famille, direction, secours, à quelle heure', 3]] })),
      B.champs({ items: [['Témoins', 1], ['Suites données', 2]], cols: 1 }),
      B.signatures(['Signature du rédacteur', 'Visa de la direction']),
      B.texte('Un accident grave fait l’objet d’une déclaration aux services de l’État selon la procédure en vigueur : cette fiche ne la remplace pas. ' + REGLE, true),
    ],
  },
];
