const { B } = require('../dsl.js');
const { TOUS, JOURS5, ADAPTER } = require('./commun.js');

const base = { cat: 'animation', theme: 'Animation', metiers: ['animation', 'education', 'associatif', 'protection'] };

const jeux = (liste) => B.tableau({ cols: [{ t: 'Jeu', w: 20 }, { t: 'Comment on joue', w: 56 }, { t: 'Âge · durée', w: 24 }], lignes: liste, premiereGras: true });

module.exports = [
  {
    ...base,
    id: 'fiche-de-preparation-d-activite',
    titre: 'Fiche de préparation d’activité vierge',
    description: 'La fiche que l’on remplit avant chaque activité : objectifs, public, matériel, déroulé minuté, sécurité, repli en cas de pluie.',
    publics: ['equipes'],
    metiers: TOUS,
    kicker: 'Animation · préparer',
    t1: 'Préparer', t2: 'mon activité', sous: 'la fiche à remplir avant',
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Nom de l’activité', 1], ['Date et horaire', 1], ['Public : nombre et âges', 1], ['Animateurs', 1]], cols: 2 }),
      B.cote(B.champs({ titre: 'Objectifs observables', items: [['', 3]], couleur: 'indigo' }), B.champs({ titre: 'Matériel', items: [['', 3]], couleur: 'indigo' })),
      B.tableau({ titre: 'Déroulé', cols: [{ t: 'Horaire', w: 14 }, { t: 'Ce qu’on fait', w: 56 }, { t: 'Qui', w: 30 }], vides: 5, h: 11 }),
      B.cote(B.champs({ titre: 'Sécurité et vigilance', items: [['', 3]], couleur: 'corail' }), B.champs({ titre: 'S’il pleut, si ça ne marche pas', items: [['', 3]], couleur: 'vert' })),
    ],
    lex: { outil: 'groupe', libelle: 'Préparer mon activité avec LEX' },
  },
  {
    ...base,
    id: 'programme-de-la-semaine-acm',
    titre: 'Programme de la semaine d’accueil de loisirs',
    description: 'Cinq jours, matin et après-midi, avec le thème, les sorties et les repas : à afficher pour les familles et à envoyer en tableau.',
    publics: ['enfants', 'familles', 'equipes'],
    metiers: ['animation', 'associatif', 'education'],
    kicker: 'Animation · programme',
    t1: 'Le programme', t2: 'de la semaine', sous: 'à afficher pour les familles',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.champs({ items: [['Semaine du … au …', 1], ['Thème de la semaine', 1]], cols: 2 }),
      B.tableau({ feuille: 'Programme', cols: [{ t: '', w: 16 }, ...JOURS5.map((j) => ({ t: j, w: 16.8 }))], lignes: [['Matin', '', '', '', '', ''], ['Repas', '', '', '', '', ''], ['Après-midi', '', '', '', '', ''], ['À prévoir', '', '', '', '', '']], premiereGras: true, h: 26 }),
      B.texte('Le programme peut changer selon la météo et l’envie du groupe. Les sorties sont confirmées la veille.', true),
    ],
  },
  {
    ...base,
    id: 'dix-jeux-de-presentation',
    titre: '10 jeux pour se présenter et briser la glace',
    description: 'Dix jeux sans matériel pour le premier jour : la balle des prénoms, le portrait chinois, deux vérités un mensonge, et sept autres.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Animation · premier jour',
    t1: '10 jeux', t2: 'pour se présenter', sous: 'sans matériel ou presque',
    format: 'Mémo A4 · 1 page', mod: ['docx'],
    corps: [jeux([
      ['La balle des prénoms', 'On se lance une balle en disant le prénom de celui qui la reçoit. Puis deux balles en même temps.', 'Dès 6 ans · 10 min'],
      ['Le portrait chinois', 'Si j’étais un animal, une couleur, un plat… Chacun répond à trois questions.', 'Dès 8 ans · 15 min'],
      ['Deux vérités, un mensonge', 'Chacun dit trois phrases sur lui ; le groupe devine laquelle est fausse.', 'Dès 10 ans · 20 min'],
      ['La ligne des anniversaires', 'Se ranger par date d’anniversaire sans parler, par gestes.', 'Dès 8 ans · 10 min'],
      ['Le bingo humain', 'Une grille de cases : « a un frère », « aime le foot »… Trouver quelqu’un pour chaque case.', 'Dès 8 ans · 15 min'],
      ['Le prénom et le geste', 'On dit son prénom avec un geste, le groupe répète tous les précédents.', 'Dès 5 ans · 10 min'],
      ['Les points communs', 'Par deux, trouver trois points communs, puis les présenter au groupe.', 'Dès 9 ans · 15 min'],
      ['La toile', 'Une pelote passe de main en main avec une info sur soi ; on finit par une toile.', 'Dès 6 ans · 15 min'],
      ['Le blason', 'Chacun dessine un blason en quatre parties : ce que j’aime, ce que je sais faire, un rêve, un lieu.', 'Dès 7 ans · 25 min'],
      ['Le salut du monde', 'Se saluer de cinq façons différentes en se croisant dans l’espace.', 'Dès 5 ans · 5 min'],
    ])],
    lex: { outil: 'groupe', libelle: 'Adapter un jeu à mon groupe avec LEX' },
  },
  {
    ...base,
    id: 'dix-jeux-calmes',
    titre: '10 jeux calmes pour revenir au calme',
    description: 'Dix jeux pour la fin de journée, l’attente ou après un temps agité : le roi du silence, le dessin dans le dos, la statue, et sept autres.',
    publics: ['petite-enfance', 'enfants', 'ados'],
    kicker: 'Animation · retour au calme',
    t1: '10 jeux', t2: 'calmes', sous: 'pour faire redescendre le groupe',
    format: 'Mémo A4 · 1 page', mod: ['docx'],
    corps: [jeux([
      ['Le roi du silence', 'Le roi désigne en silence celui qui bouge ou parle ; le dernier immobile devient roi.', 'Dès 4 ans · 10 min'],
      ['Le dessin dans le dos', 'On dessine une forme simple dans le dos du voisin, qui la fait passer. On compare au bout.', 'Dès 6 ans · 10 min'],
      ['Les statues', 'Musique : on danse ; silence : on se fige. Ralentir la musique à chaque tour.', 'Dès 3 ans · 10 min'],
      ['Qu’est-ce qui a changé ?', 'Un joueur sort, on change un détail dans la pièce, il doit le trouver.', 'Dès 5 ans · 10 min'],
      ['La météo du corps', 'L’adulte raconte une météo que les enfants font avec leurs mains sur le dos du voisin.', 'Dès 3 ans · 5 min'],
      ['Le téléphone arabe', 'Un message chuchoté fait le tour du cercle ; on compare le départ et l’arrivée.', 'Dès 5 ans · 10 min'],
      ['Le Kim des objets', 'Dix objets sur un plateau, 30 secondes pour regarder, on en retire un.', 'Dès 5 ans · 10 min'],
      ['La respiration du ballon', 'On gonfle un ballon imaginaire en inspirant, on le dégonfle en soufflant, cinq fois.', 'Dès 3 ans · 5 min'],
      ['Le mot qui suit', 'Chacun ajoute un mot pour construire une histoire, à voix basse.', 'Dès 7 ans · 10 min'],
      ['Le coloriage à deux', 'Deux enfants colorient le même dessin sans se parler.', 'Dès 4 ans · 15 min'],
    ])],
  },
  {
    ...base,
    id: 'dix-jeux-d-exterieur',
    titre: '10 jeux d’extérieur pour un grand groupe',
    description: 'Dix jeux pour la cour ou le parc, de 10 à 30 enfants : béret, poule-renard-vipère, drapeaux, épervier, et six autres, avec la sécurité.',
    publics: ['enfants', 'ados'],
    kicker: 'Animation · extérieur',
    t1: '10 jeux', t2: 'd’extérieur', sous: 'de 10 à 30 enfants',
    format: 'Mémo A4 · 1 page', mod: ['docx'],
    corps: [
      jeux([
        ['Le béret', 'Deux équipes numérotées ; à l’appel d’un numéro, chacun tente de ramener le foulard sans être touché.', 'Dès 7 ans · 20 min'],
        ['Poule, renard, vipère', 'Trois équipes : la poule attrape la vipère, la vipère le renard, le renard la poule.', 'Dès 7 ans · 25 min'],
        ['La balle aux prisonniers', 'Toucher un adversaire avec la balle l’envoie en prison ; on le libère en attrapant une passe.', 'Dès 8 ans · 20 min'],
        ['Les drapeaux', 'Chaque équipe garde son drapeau et tente de prendre celui de l’autre camp.', 'Dès 8 ans · 30 min'],
        ['L’épervier', 'L’épervier au milieu attrape ceux qui traversent ; chaque attrapé devient épervier.', 'Dès 6 ans · 15 min'],
        ['Le loup glacé', 'Touché par le loup, on se fige ; un camarade nous libère en passant sous nos jambes.', 'Dès 5 ans · 15 min'],
        ['La course de relais', 'Par équipes, un parcours à faire chacun son tour avec un objet à transmettre.', 'Dès 5 ans · 15 min'],
        ['Le parachute', 'Le groupe fait onduler une grande toile et change de place quand on appelle sa couleur.', 'Dès 3 ans · 15 min'],
        ['Un, deux, trois, soleil', 'Avancer quand le meneur tourne le dos, se figer quand il se retourne.', 'Dès 4 ans · 10 min'],
        ['La chasse aux couleurs', 'Trouver dans le parc un élément de chaque couleur de la liste.', 'Dès 4 ans · 20 min'],
      ]),
      B.puces('Sécurité', ['Terrain délimité et vérifié avant de jouer (trous, objets, bordures).', 'Eau et coin ombragé à portée, pause toutes les 20 minutes par forte chaleur.', 'Un adulte placé pour voir tout le terrain, un autre qui joue.'], 'corail'),
    ],
  },
  {
    ...base,
    id: 'kit-chasse-au-tresor',
    titre: 'Kit chasse au trésor : déroulé et indices',
    description: 'Le déroulé d’une chasse au trésor en équipes et huit indices à découper, avec des cases vierges pour écrire les vôtres.',
    publics: ['enfants'],
    kicker: 'Animation · grand jeu',
    t1: 'Kit', t2: 'chasse au trésor', sous: 'huit indices, un trésor',
    format: 'Kit A4 · 2 pages', mod: ['docx'],
    pages: [
      [
        B.bandeau('<b>Le principe :</b> chaque indice mène au lieu suivant. Les équipes partent à quelques minutes d’écart ou suivent les indices dans un ordre différent, pour ne pas se suivre.'),
        B.cote(B.champs({ titre: 'À préparer la veille', items: [['Lieux des indices, ordre pour chaque équipe', 4]], couleur: 'indigo' }), B.puces('Matériel', ['Huit enveloppes par équipe, de la couleur de l’équipe.', 'Un trésor à partager : goûter, médailles en carton, livre du groupe.', 'Un sifflet et une montre pour l’adulte référent.'], 'indigo')),
        B.etapes('Déroulé', [['10 min', 'Constitution des équipes, règles : on reste ensemble, on ne prend que les enveloppes de sa couleur.'], ['45 min', 'La chasse : chaque indice résolu donne une lettre du mot final.'], ['10 min', 'Les équipes reconstituent le mot, qui dit où est le trésor.'], ['10 min', 'Trésor partagé entre toutes les équipes, et retour au calme.']]),
        B.puces('Vigilance', ['Les lieux sont visibles par un adulte ou gardés.', 'Un point de ralliement connu de tous, et un signal de rappel.', 'Le trésor se partage : aucune équipe ne repart sans rien.'], 'corail'),
      ],
      [
        B.cartes({ titre: 'Indices à découper (exemples, à adapter à vos lieux)', items: [['🚪', 'Là où l’on entre et l’on sort, cherche sous le paillasson.'], ['🌳', 'Je suis le plus grand du jardin, regarde à mes pieds.'], ['🍽️', 'On s’y retrouve à midi, regarde sous la troisième chaise.'], ['📚', 'Je suis plein d’histoires, ouvre-moi à la page 10.'], ['🚰', 'On me tourne pour boire, regarde derrière moi.'], ['🪑', 'Quatre pieds mais je ne marche pas, cherche dessous.'], ['🧺', 'Je range les ballons, fouille-moi.'], ['🖼️', 'Je suis accrochée au mur, regarde derrière moi.']], cols: 4, h: 48 }),
        B.cartes({ titre: 'Vos propres indices', items: [], vides: 4, cols: 4, h: 44 }),
      ],
    ],
    lex: { outil: 'grandjeu', libelle: 'Créer ma chasse au trésor avec LEX' },
  },
  {
    ...base,
    id: 'kit-veillee-contes',
    titre: 'Kit veillée contes et histoires',
    description: 'Une veillée d’une heure : l’ambiance, le conteur, l’histoire à plusieurs voix, le moment calme de fin, et les rôles de l’équipe.',
    publics: ['enfants', 'ados'],
    metiers: ['animation', 'associatif', 'education'],
    kicker: 'Animation · veillée',
    t1: 'Kit', t2: 'veillée contes', sous: 'une heure avant d’aller dormir',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.bandeau('<b>L’idée :</b> une veillée qui fait baisser l’énergie au lieu de la monter. Lumière tamisée, cercle, une histoire partagée, et la fin qui mène au coucher.'),
      B.etapes('Déroulé', [['10 min', 'Installation : coussins en cercle, une seule source de lumière, le rituel du bâton de parole.'], ['20 min', 'Le conte lu ou raconté par un animateur, avec des pauses où les enfants font les bruitages.'], ['20 min', 'L’histoire à plusieurs voix : chacun ajoute une phrase à son tour, sans obligation.'], ['10 min', 'Fin calme : une musique douce, une phrase de chacun sur sa journée, et on monte se coucher.']]),
      B.cote(B.puces('Rôles de l’équipe', ['Le conteur.', 'L’adulte placé près des plus sensibles, qui peut sortir avec un enfant.', 'L’adulte qui prépare le coucher pendant la fin de veillée.'], 'indigo'), B.puces('Vigilance', ['Pas d’histoire qui fait peur pour les plus jeunes, ou alors annoncée et choisie.', 'Une lampe de poche accessible, jamais le noir total.', 'Un enfant qui ne veut pas parler passe son tour, sans commentaire.'], 'corail')),
    ],
  },
  {
    ...base,
    id: 'rallye-photo',
    titre: 'Rallye photo : la feuille de route des équipes',
    description: 'Douze défis photo à réaliser en équipe dans un quartier ou un parc, avec les règles et une case pour l’heure de retour.',
    publics: ['enfants', 'ados'],
    kicker: 'Animation · sortie',
    t1: 'Rallye', t2: 'photo', sous: 'douze défis, une équipe',
    format: 'Feuille de route A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Nom de l’équipe', 1], ['Adulte référent et son téléphone', 1], ['Heure de départ', 1], ['Heure de retour au point de rendez-vous', 1]], cols: 2 }),
      B.cocher('Les douze défis', ['Toute l’équipe sur une photo, sans tenir l’appareil.', 'Quelque chose de rouge, de jaune et de bleu sur la même photo.', 'Une forme de cœur trouvée dans la nature.', 'L’équipe qui forme une lettre de l’alphabet.', 'Un panneau avec un chiffre.', 'Le plus vieil objet trouvé.', 'Une photo prise d’en bas, allongé.', 'L’équipe qui saute en même temps.', 'Une ombre rigolote.', 'Quelque chose de tout petit en gros plan.', 'Une reproduction d’une œuvre d’art avec vos corps.', 'Votre photo préférée de la journée, choisie ensemble.'], { cols: 2 }),
      B.puces('Règles', ['On ne photographie pas les passants sans leur accord.', 'L’équipe reste ensemble, avec son adulte.', 'Retour au point de rendez-vous à l’heure, même si tout n’est pas fait.'], 'corail'),
    ],
  },
  {
    ...base,
    id: 'projet-d-animation-sur-un-cycle',
    titre: 'Projet d’animation sur un cycle',
    description: 'Le projet d’une activité sur plusieurs semaines : intention, objectifs, séances, évaluation, à présenter à l’équipe ou au directeur.',
    publics: ['equipes'],
    metiers: TOUS,
    kicker: 'Animation · projet',
    t1: 'Projet', t2: 'd’animation', sous: 'sur plusieurs séances',
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Titre du projet', 1], ['Animateur', 1], ['Public', 1], ['Période et nombre de séances', 1]], cols: 2 }),
      B.champs({ titre: 'Pourquoi ce projet', items: [['Ce qu’on a remarqué, ce que le projet doit permettre', 3]], couleur: 'indigo' }),
      B.tableau({ titre: 'Les séances', cols: [{ t: 'Séance', w: 12 }, { t: 'Contenu', w: 48 }, { t: 'Objectif de la séance', w: 40 }], vides: 6, h: 11 }),
      B.cote(B.champs({ titre: 'Comment on évalue', items: [['', 3]], couleur: 'vert' }), B.champs({ titre: 'Moyens et budget', items: [['', 3]] })),
    ],
    lex: { outil: 'collective', libelle: 'Construire mon projet avec LEX' },
  },
];
