const { B } = require('../dsl.js');

const base = { cat: 'associations', theme: 'Vie associative', metiers: ['associatif', 'social', 'animation'], publics: ['equipes', 'adultes'] };

const CHARGES = ['Achats (matériel, fournitures)', 'Locations', 'Assurance', 'Déplacements', 'Communication', 'Rémunérations et charges', 'Intervenants extérieurs', 'Autres charges'];
const PRODUITS = ['Participation des usagers', 'Subvention de la commune', 'Subvention du département', 'Subvention de l’État ou de la CAF', 'Fondations et mécénat', 'Fonds propres de l’association', 'Autres produits'];

module.exports = [
  {
    ...base,
    id: 'budget-previsionnel-d-une-action',
    titre: 'Budget prévisionnel d’une action',
    description: 'Charges et produits en deux colonnes, totaux et équilibre calculés dans la version Excel : la base d’une demande de subvention.',
    kicker: 'Associations · budget',
    t1: 'Budget', t2: 'prévisionnel', sous: 'charges = produits',
    format: 'Tableau A4 · 1 page', mod: ['xlsx', 'docx'],
    corps: [
      B.champs({ items: [['Action', 1], ['Période', 1]], cols: 2 }),
      B.cote(
        B.tableau({ feuille: 'Charges', titre: 'Charges', cols: [{ t: 'Poste', w: 70 }, { t: 'Montant (€)', w: 30 }], lignes: CHARGES.map((c) => [c, '']), total: [1], euros: [1], h: 7 }),
        B.tableau({ feuille: 'Produits', titre: 'Produits', cols: [{ t: 'Origine', w: 70 }, { t: 'Montant (€)', w: 30 }], lignes: PRODUITS.map((c) => [c, '']), total: [1], euros: [1], h: 7 }),
      ),
      B.tableau({ feuille: 'Équilibre', titre: 'Équilibre', cols: [{ t: '', w: 70 }, { t: 'Montant (€)', w: 30 }], lignes: [['Total des charges', `='Charges'!B${4 + CHARGES.length}`], ['Total des produits', `='Produits'!B${4 + PRODUITS.length}`], ['Écart (doit être à zéro)', '=B5-B4']], euros: [1], premiereGras: true }),
      B.texte('Les contributions en nature (bénévolat valorisé, locaux prêtés) s’ajoutent de part et d’autre, à montant égal.', true),
    ],
  },
  {
    ...base,
    id: 'feuille-d-emargement',
    titre: 'Feuille d’émargement',
    description: 'Nom, structure, signature : la feuille de présence pour une réunion, une formation interne ou une assemblée.',
    publics: ['equipes', 'adultes'],
    metiers: ['associatif', 'social', 'animation', 'education', 'protection', 'handicap'],
    kicker: 'Associations · présence',
    t1: 'Feuille', t2: 'd’émargement', sous: 'une signature par personne présente',
    format: 'Tableau A4 · 1 page', mod: ['docx', 'xlsx'],
    corps: [
      B.champs({ items: [['Objet', 1], ['Date et lieu', 1]], cols: 2 }),
      B.tableau({ feuille: 'Émargement', cols: [{ t: 'Nom et prénom', w: 36 }, { t: 'Structure ou qualité', w: 30 }, { t: 'Signature', w: 34 }], vides: 18, h: 10 }),
    ],
  },
  {
    ...base,
    id: 'modele-convocation-assemblee-generale',
    titre: 'Modèle : convocation à l’assemblée générale',
    description: 'La convocation avec la date, le lieu, l’ordre du jour et le pouvoir à retourner, à adapter selon vos statuts.',
    kicker: 'Associations · assemblée générale',
    t1: 'Convocation', t2: 'assemblée générale', sous: 'selon les délais de vos statuts', modele: true,
    format: 'Modèle A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Nom de l’association, adresse', 2], ['Lieu et date d’envoi', 1]], cols: 2 }),
      B.texte('Madame, Monsieur, cher adhérent,'),
      B.champs({ items: [['Vous êtes convoqué(e) à l’assemblée générale ordinaire qui se tiendra le', 1], ['à (heure et lieu)', 1]], cols: 1 }),
      B.champs({ titre: 'Ordre du jour', items: [['1. Rapport moral', 1], ['2. Rapport d’activité', 1], ['3. Rapport financier et approbation des comptes', 1], ['4. Montant de la cotisation', 1], ['5. Renouvellement des membres du conseil d’administration', 1], ['6. Questions diverses', 1]], cols: 1, couleur: 'indigo' }),
      B.zone('Pouvoir, si vous ne pouvez pas venir', 32, 'Je soussigné(e) ______________________ donne pouvoir à ______________________ pour me représenter et voter en mon nom. Date et signature :'),
      B.texte('Les délais de convocation, le quorum et les règles de vote sont ceux de vos statuts : vérifiez-les avant l’envoi.', true),
    ],
  },
  {
    ...base,
    id: 'trame-proces-verbal-d-assemblee-generale',
    titre: 'Trame : procès-verbal d’assemblée générale',
    description: 'Présents et représentés, quorum, chaque résolution avec le résultat du vote, et les signatures du président et du secrétaire.',
    kicker: 'Associations · assemblée générale',
    t1: 'Procès-verbal', t2: 'd’assemblée générale', sous: 'chaque vote avec son résultat', modele: true,
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Association', 1], ['Date, heure, lieu', 1], ['Présidée par', 1], ['Secrétaire de séance', 1], ['Membres présents / représentés', 1], ['Quorum atteint (oui, non, non requis)', 1]], cols: 2 }),
      B.tableau({ titre: 'Résolutions', cols: [{ t: 'N°', w: 6 }, { t: 'Résolution', w: 54 }, { t: 'Pour', w: 10 }, { t: 'Contre', w: 10 }, { t: 'Abstention', w: 10 }, { t: 'Adoptée', w: 10 }], vides: 6, h: 14 }),
      B.champs({ titre: 'Questions diverses et remarques', items: [['', 3]] }),
      B.signatures(['Le président', 'Le secrétaire']),
    ],
  },
  {
    ...base,
    id: 'suivi-des-adhesions',
    titre: 'Tableau de suivi des adhésions',
    description: 'Adhérents, date d’adhésion, cotisation réglée, moyen de paiement, reçu remis : avec le total des cotisations calculé.',
    kicker: 'Associations · adhésions',
    t1: 'Suivi', t2: 'des adhésions', sous: 'qui est à jour de sa cotisation',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx'], paysage: true,
    corps: [
      B.tableau({ feuille: 'Adhésions', cols: [{ t: 'Nom et prénom', w: 22 }, { t: 'Date d’adhésion', w: 12 }, { t: 'Cotisation (€)', w: 12 }, { t: 'Moyen de paiement', w: 14 }, { t: 'Reçu remis', w: 10 }, { t: 'Contact', w: 30 }], vides: 12, h: 7, total: [2], euros: [2] }),
      B.texte('Ce tableau contient des données personnelles : gardez-le dans un dossier protégé, et ne conservez les adhérents partis que le temps prévu par votre association.', true),
    ],
  },
  {
    ...base,
    id: 'fiche-d-accueil-d-un-benevole',
    titre: 'Fiche d’accueil d’un bénévole',
    description: 'Disponibilités, envies, compétences, contact en cas d’urgence et engagement de confidentialité, sur une page.',
    kicker: 'Associations · bénévoles',
    t1: 'Fiche', t2: 'bénévole', sous: 'bienvenue parmi nous',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Nom et prénom', 1], ['Téléphone et e-mail', 1], ['Personne à prévenir en cas d’urgence', 1], ['Arrivé le', 1]], cols: 2 }),
      B.cote(B.champs({ titre: 'Mes disponibilités', items: [['Jours, horaires, fréquence', 3]], couleur: 'indigo' }), B.champs({ titre: 'Ce que j’aimerais faire', items: [['', 3]], couleur: 'vert' })),
      B.champs({ titre: 'Ce que je sais faire', items: [['Compétences, expériences, langues parlées', 2]] }),
      B.cocher('Engagements', ['Je respecte la confidentialité de ce que je vois et entends.', 'Je préviens mon référent si je ne peux pas venir.', 'J’ai reçu les consignes de sécurité.']),
      B.signatures(['Le bénévole', 'Le référent de l’association']),
    ],
  },
  {
    ...base,
    id: 'retroplanning-d-un-evenement',
    titre: 'Rétroplanning d’un événement',
    description: 'De J-60 au jour J : les tâches à lancer, qui s’en charge et où on en est, pour une fête, un forum ou une journée portes ouvertes.',
    kicker: 'Associations · événement',
    t1: 'Rétroplanning', t2: 'd’un événement', sous: 'de J-60 au jour J',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.champs({ items: [['Événement', 1], ['Date du jour J', 1]], cols: 2 }),
      B.tableau({ feuille: 'Rétroplanning', cols: [{ t: 'Quand', w: 10 }, { t: 'Tâche', w: 42 }, { t: 'Qui', w: 16 }, { t: 'Fait', w: 8 }, { t: 'Remarque', w: 24 }], lignes: [['J-60', 'Fixer la date, le lieu et le budget'], ['J-45', 'Réserver la salle, le matériel, les assurances'], ['J-30', 'Lancer la communication : affiche, réseaux, partenaires'], ['J-30', 'Demander les autorisations (mairie, buvette, voie publique)'], ['J-21', 'Recruter les bénévoles et répartir les rôles'], ['J-14', 'Relancer les partenaires et la presse locale'], ['J-7', 'Confirmer prestataires et bénévoles, imprimer les documents'], ['J-2', 'Courses, matériel, plan de la salle'], ['Jour J', 'Installation, accueil, sécurité, rangement'], ['J+7', 'Bilan, remerciements, photos partagées']].map((l) => [...l, '', '', '']), premiereGras: true, h: 9 }),
    ],
  },
  {
    ...base,
    id: 'plan-de-communication-simple',
    titre: 'Plan de communication en une page',
    description: 'Le message, les publics, les canaux, le calendrier des publications et qui s’en charge : un plan simple pour une petite association.',
    kicker: 'Associations · communication',
    t1: 'Plan', t2: 'de communication', sous: 'un message, des publics, un calendrier',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.champs({ items: [['Ce qu’on veut faire savoir, en une phrase', 1], ['À qui (publics)', 1]], cols: 2, couleur: 'indigo' }),
      B.tableau({ feuille: 'Calendrier', cols: [{ t: 'Date', w: 10 }, { t: 'Canal', w: 16 }, { t: 'Contenu', w: 40 }, { t: 'Qui', w: 14 }, { t: 'Publié', w: 8 }, { t: 'Résultat', w: 12 }], vides: 10, h: 10 }),
      B.texte('Canaux possibles : affiche, lettre d’information, Facebook, Instagram, LinkedIn, site, presse locale, bouche-à-oreille des partenaires.', true),
    ],
  },
  {
    ...base,
    id: 'trame-proces-verbal-de-conseil-d-administration',
    titre: 'Trame : procès-verbal de conseil d’administration',
    description: 'Présents, excusés, ordre du jour, décisions prises avec le vote, et signatures : le compte rendu officiel d’un conseil d’administration.',
    kicker: 'Associations · conseil',
    t1: 'Procès-verbal', t2: 'de conseil d’administration', sous: 'chaque décision avec son vote', modele: true,
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Association', 1], ['Date, heure, lieu', 1], ['Présents', 1], ['Excusés, représentés', 1]], cols: 2 }),
      B.tableau({ titre: 'Décisions', cols: [{ t: 'Point', w: 34 }, { t: 'Décision prise', w: 42 }, { t: 'Vote (pour, contre, abstention)', w: 24 }], vides: 6, h: 14 }),
      B.champs({ items: [['Prochaine réunion', 1]] }),
      B.signatures(['Le président', 'Le secrétaire']),
    ],
  },
  {
    ...base,
    id: 'recu-de-cotisation',
    titre: 'Reçu de cotisation à remettre à l’adhérent',
    description: 'Le reçu de paiement de la cotisation, en double exemplaire : un pour l’adhérent, un pour l’association. Ce n’est pas un reçu fiscal.',
    kicker: 'Associations · adhésions',
    t1: 'Reçu', t2: 'de cotisation', sous: 'deux exemplaires par page', modele: true,
    format: 'Modèle A4 · 2 par page', mod: ['docx'],
    corps: ['Exemplaire de l’adhérent', 'Exemplaire de l’association'].map((ex) => B.champs({ titre: ex, items: [['Association, adresse', 1], ['Reçu n°', 1], ['Reçu de', 1], ['La somme de (€)', 1], ['Au titre de la cotisation pour la période', 1], ['Mode de paiement et date', 1], ['Signature du trésorier', 1]], cols: 2, couleur: 'indigo' })).concat([B.texte('Ce reçu atteste d’un paiement. Il ne vaut pas reçu fiscal : seul un organisme qui y a droit peut délivrer un reçu ouvrant une réduction d’impôt, sur le modèle officiel.', true)]),
  },
];
