const { B } = require('../dsl.js');
const { TOUS, EDUC, ENF, FACTUEL, CLAIR, OBJECTIFS } = require('./commun.js');

const base = { cat: 'ecrits', theme: 'Écrits professionnels', metiers: EDUC };

module.exports = [
  {
    ...base,
    id: 'trame-rapport-de-situation',
    titre: 'Trame : rapport de situation',
    description: 'Les rubriques d’un rapport de situation, avec ce qu’on met dans chacune : contexte, observations, points d’appui, préoccupations, propositions.',
    publics: ['equipes'],
    metiers: ['protection', 'education', 'social', 'handicap'],
    kicker: 'Écrits · rapport',
    t1: 'Trame', t2: 'rapport de situation', sous: 'équilibré et vérifiable',
    format: 'Trame A4 · 2 pages', mod: ['docx'], fictif: false,
    pages: [
      [
        B.bandeau('<b>Ce que le lecteur doit trouver :</b> des faits datés, la parole de la personne et de sa famille, ce qui va bien autant que ce qui inquiète, et des propositions argumentées. Ce rapport peut être lu par la personne et sa famille : écrivez en le sachant.'),
        B.champs({ titre: '1. Identification', items: [['Personne accompagnée', 1], ['Service et référent', 1], ['Période couverte', 1], ['Destinataire', 1]], cols: 2 }),
        B.champs({ titre: '2. Le contexte', items: [['Le cadre de l’accompagnement, depuis quand, pourquoi', 4]] }),
        B.champs({ titre: '3. Ce qui a été observé', items: [['Des faits datés, par domaine : vie quotidienne, scolarité ou travail, relations, santé (sans diagnostic)', 7]], couleur: 'indigo' }),
      ],
      [
        B.cote(B.champs({ titre: '4. Points d’appui', items: [['Ce qui va, ce sur quoi on peut compter', 5]], couleur: 'vert' }), B.champs({ titre: '5. Préoccupations', items: [['Ce qui inquiète, avec les faits qui le montrent', 5]], couleur: 'corail' })),
        B.champs({ titre: '6. La parole de la personne et de sa famille', items: [['Ce qu’elles disent, entre guillemets, et leur avis sur les propositions', 4]] }),
        B.champs({ titre: '7. Propositions', items: [['Ce que l’équipe propose, et pourquoi', 4]], couleur: 'indigo' }),
        B.signatures(['Rédigé par, le', 'Relu par']),
      ],
    ],
    lex: { outil: 'factuel', libelle: 'Rendre mon rapport plus factuel avec LEX' },
  },
  {
    ...base,
    id: 'trame-projet-personnalise',
    titre: 'Trame : projet personnalisé',
    description: 'Les attentes de la personne d’abord, puis les objectifs observables, les moyens, les échéances et les signatures.',
    publics: ['equipes'],
    metiers: ['education', 'handicap', 'protection', 'social'],
    kicker: 'Écrits · projet',
    t1: 'Trame', t2: 'projet personnalisé', sous: 'construit avec la personne',
    format: 'Trame A4 · 2 pages', mod: ['docx'],
    pages: [
      [
        B.champs({ titre: 'La personne', items: [['Nom et prénom', 1], ['Date de la rencontre', 1], ['Présents', 1], ['Référent', 1]], cols: 2 }),
        B.champs({ titre: 'Ce que la personne souhaite, avec ses mots', items: [['', 5]], couleur: 'indigo' }),
        B.champs({ titre: 'Ce que souhaite sa famille ou son représentant', items: [['', 3]] }),
        B.cote(B.champs({ titre: 'Ce qui va bien', items: [['', 4]], couleur: 'vert' }), B.champs({ titre: 'Ce qui est difficile', items: [['', 4]], couleur: 'corail' })),
      ],
      [
        B.tableau({ titre: 'Objectifs retenus ensemble', cols: [{ t: 'Objectif', w: 26 }, { t: 'On saura que c’est atteint quand', w: 26 }, { t: 'Moyens', w: 20 }, { t: 'Qui', w: 12 }, { t: 'Échéance', w: 16 }], vides: 5, h: 18 }),
        B.champs({ items: [['Date du prochain point', 1], ['Avis de la personne sur ce projet', 2]], cols: 1 }),
        B.signatures(['La personne', 'Son représentant', 'Le référent']),
      ],
    ],
    lex: OBJECTIFS,
  },
  {
    ...base,
    id: 'trame-note-d-incident',
    titre: 'Trame : note d’incident',
    description: 'Ce qui s’est passé, dans l’ordre, qui était là, ce qui a été fait tout de suite, qui a été prévenu : sans interprétation.',
    publics: ['equipes'],
    metiers: TOUS,
    kicker: 'Écrits · incident',
    t1: 'Trame', t2: 'note d’incident', sous: 'à écrire le jour même',
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Date et heure', 1], ['Lieu', 1], ['Rédigé par', 1], ['Témoins présents', 1]], cols: 2 }),
      B.champs({ titre: 'Ce qui s’est passé, dans l’ordre', items: [['Des faits, des paroles entre guillemets. Pas de jugement ni d’intention prêtée.', 7]], couleur: 'indigo' }),
      B.champs({ titre: 'Ce qui a été fait tout de suite', items: [['', 3]] }),
      B.cote(B.champs({ titre: 'Personnes prévenues', items: [['Qui, à quelle heure', 3]] }), B.champs({ titre: 'Suites à donner', items: [['', 3]] })),
      B.texte('La déclaration aux autorités, quand elle est nécessaire, suit la procédure de votre établissement. Cette note ne la remplace pas.', true),
    ],
    lex: FACTUEL,
  },
  {
    ...base,
    id: 'modele-courrier-aux-parents',
    titre: 'Modèle : courrier aux parents',
    description: 'Un courrier clair en cinq paragraphes pour informer, demander une autorisation ou proposer un rendez-vous, avec coupon-réponse.',
    publics: ['familles', 'equipes'],
    metiers: ['education', 'protection', 'handicap', 'animation'],
    kicker: 'Écrits · familles',
    t1: 'Modèle', t2: 'courrier aux parents', sous: 'clair, poli, court', modele: true,
    format: 'Modèle A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Structure, adresse, téléphone', 2], ['Lieu et date', 1]], cols: 2 }),
      B.texte('Madame, Monsieur,'),
      B.champs({ items: [['1. Pourquoi nous vous écrivons, en une phrase', 2], ['2. Ce qui est prévu : quoi, quand, où, avec qui', 3], ['3. Ce que nous vous demandons, et pour quand', 2], ['4. Qui contacter pour une question', 1]], cols: 1 }),
      B.texte('Nous restons à votre disposition et vous prions d’agréer, Madame, Monsieur, nos salutations distinguées.'),
      B.signatures(['Nom, fonction, signature']),
      B.zone('Coupon-réponse à rapporter', 30, 'Je soussigné(e) ______________________ parent de ______________________ ☐ accepte ☐ n’accepte pas. Date et signature :'),
    ],
    lex: CLAIR,
  },
  {
    ...base,
    id: 'page-cahier-de-liaison',
    titre: 'Page de cahier de liaison',
    description: 'Une page par jour entre la structure et la famille : la journée, le repas, le sommeil, un mot de chacun.',
    publics: ['petite-enfance', 'enfants', 'familles'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Écrits · liaison',
    t1: 'Cahier', t2: 'de liaison', sous: 'un mot de chaque côté',
    format: 'Page A4 · 2 jours par page', mod: ['docx'],
    corps: [
      ...[1, 2].flatMap(() => [
        B.champs({ items: [['Date', 1], ['Rempli par', 1]], cols: 2 }),
        B.cote(
          B.champs({ titre: 'À la structure aujourd’hui', items: [['Activités, repas, sommeil, moments forts', 4]], couleur: 'indigo' }),
          B.champs({ titre: 'À la maison', items: [['Un mot de la famille', 4]], couleur: 'vert' }),
        ),
      ]),
    ],
  },
  {
    ...base,
    id: 'memo-mots-a-remplacer',
    titre: 'Mémo : 12 mots à remplacer dans un écrit',
    description: 'Agressif, manipulateur, carencé, ne veut pas… : douze mots qui jugent, et par quoi les remplacer pour décrire ce qu’on a vu.',
    publics: ['equipes'],
    metiers: TOUS,
    kicker: 'Écrits · mémo',
    t1: '12 mots', t2: 'à remplacer', sous: 'décrire plutôt que qualifier', fictif: true,
    format: 'Mémo A4 · 1 page', mod: ['docx'],
    corps: [
      B.tableau({ cols: [{ t: 'Au lieu d’écrire', w: 28 }, { t: 'Le problème', w: 30 }, { t: 'Écrivez plutôt (exemple fictif)', w: 42 }], lignes: [
        ['Il est agressif', 'Un jugement sur la personne', 'Il a crié « laisse-moi » et a poussé la table.'],
        ['Elle est manipulatrice', 'Une intention prêtée', 'Elle a demandé la même chose à trois adultes différents.'],
        ['Il ne veut pas', 'On ne voit pas une volonté', 'Il est resté assis quand on a annoncé le départ.'],
        ['Comportement inadapté', 'Ne dit pas ce qui s’est passé', 'Elle a déchiré sa feuille pendant la consigne.'],
        ['Carencé', 'Un mot qui étiquette', 'Il a demandé trois fois s’il y aurait un goûter.'],
        ['Mère défaillante', 'Un verdict, sans faits', 'Madame n’est pas venue aux deux derniers rendez-vous.'],
        ['Il fait des crises', 'Trop vague pour agir', 'Lundi à 10 h, il a pleuré et frappé le mur pendant 5 minutes.'],
        ['Elle est dans la toute-puissance', 'Un jargon qui interprète', 'Elle a refusé quatre consignes sur cinq ce matin.'],
        ['Il est fermé', 'Une impression', 'Il a répondu « je sais pas » à chaque question.'],
        ['Bonne participation', 'Ne se vérifie pas', 'Elle a proposé deux idées et a aidé à ranger.'],
        ['Il semble aller mieux', 'Sur quoi repose ce « mieux » ?', 'Il dort sans se réveiller depuis une semaine, dit l’équipe de nuit.'],
        ['Problématique psychique', 'Un diagnostic sous signature éducative', 'Rapportez le diagnostic existant en citant qui l’a posé, ou décrivez.'],
      ], premiereGras: true }),
      B.aretenir('Trois réflexes', ['Le test de la caméra : aurait-elle filmé ce que j’écris ?', 'Une hypothèse s’annonce : « nous faisons l’hypothèse que… ».', 'Un écrit équilibré dit aussi ce qui va bien.']),
    ],
    lex: FACTUEL,
  },
  {
    ...base,
    id: 'fiche-de-liaison-ecole',
    titre: 'Fiche de liaison avec l’école',
    description: 'Ce qui aide l’élève, ce qui le met en difficulté, qui contacter : une page à partager avec l’enseignant, avec l’accord de la famille.',
    publics: ['enfants', 'ados', 'familles'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Écrits · école',
    t1: 'Fiche', t2: 'de liaison école', sous: 'avec l’accord de la famille',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Élève', 1], ['Classe et enseignant', 1], ['Structure et référent', 1], ['Date', 1]], cols: 2 }),
      B.cote(B.champs({ titre: 'Ce qui l’aide en classe', items: [['', 5]], couleur: 'vert' }), B.champs({ titre: 'Ce qui le met en difficulté', items: [['', 5]], couleur: 'corail' })),
      B.champs({ titre: 'Ce qu’on a décidé ensemble', items: [['Les adaptations, qui fait quoi', 3]], couleur: 'indigo' }),
      B.champs({ items: [['Contact à la structure', 1], ['Contact à l’école', 1]], cols: 2 }),
      B.cocher('', ['La famille a donné son accord pour le partage de cette fiche.']),
      B.texte('Ne mettez ici que ce qui est utile à la classe : ni diagnostic, ni histoire familiale.', true),
    ],
  },
  {
    ...base,
    id: 'trame-compte-rendu-de-visite-a-domicile',
    titre: 'Trame : compte rendu de visite à domicile',
    description: 'Qui était présent, ce qui a été vu et dit, ce qui a été convenu, la prochaine étape : en restant sur les faits.',
    publics: ['equipes', 'familles'],
    metiers: ['social', 'protection', 'education', 'handicap'],
    kicker: 'Écrits · visite',
    t1: 'Trame', t2: 'visite à domicile', sous: 'ce qu’on a vu, ce qu’on a convenu',
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Date et durée', 1], ['Professionnels présents', 1], ['Personnes présentes au domicile', 1], ['Objet de la visite', 1]], cols: 2 }),
      B.champs({ titre: 'Ce qui a été observé', items: [['Des faits, sans jugement sur le logement ou le mode de vie', 5]], couleur: 'indigo' }),
      B.champs({ titre: 'Ce qui a été dit', items: [['Entre guillemets', 3]] }),
      B.cote(B.champs({ titre: 'Ce qui a été convenu', items: [['', 3]], couleur: 'vert' }), B.champs({ titre: 'Prochaine étape', items: [['', 3]] })),
    ],
    lex: FACTUEL,
  },
];
