const { B } = require('../dsl.js');
const { ENF, EDUC, ADAPTER } = require('./commun.js');

const base = { cat: 'emotions', theme: 'Émotions', metiers: ENF };

module.exports = [
  {
    ...base,
    id: 'thermometre-de-la-colere',
    titre: 'Thermomètre de la colère',
    description: 'Cinq niveaux, du calme à l’explosion : ce que je ressens dans mon corps et ce qui m’aide, écrit avec la personne.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Émotions · repérer la colère',
    t1: 'Mon thermomètre', t2: 'de la colère', sous: 'je repère, j’agis tôt',
    format: 'Affiche A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.echelle('', [
        ['#d9454b', 'J’explose', 'Ce que je ressens : ____________ · Ce qui m’aide : ____________'],
        ['#f08a3c', 'Je bous', 'Ce que je ressens : ____________ · Ce qui m’aide : ____________'],
        ['#f4c542', 'Ça chauffe', 'Ce que je ressens : ____________ · Ce qui m’aide : ____________'],
        ['#7cb342', 'Je suis agacé', 'Ce que je ressens : ____________ · Ce qui m’aide : ____________'],
        ['#1f8a5b', 'Je suis calme', 'Ce que je ressens : ____________ · Ce qui m’aide : ____________'],
      ]),
      B.texte('Le plus utile se joue aux niveaux 2 et 3 : c’est là qu’on peut encore choisir. On remplit ce thermomètre à froid, jamais pendant une crise.', true),
    ],
  },
  {
    ...base,
    id: 'roue-des-emotions',
    titre: 'Les huit émotions, avec leurs mots',
    description: 'Joie, tristesse, colère, peur, surprise, dégoût, fierté, gêne : une carte par émotion, et une ligne pour dire quand on la ressent.',
    publics: ['petite-enfance', 'enfants', 'ados'],
    kicker: 'Émotions · mettre des mots',
    t1: 'Les émotions', t2: 'et leurs mots', sous: 'je montre, je dis',
    format: 'Planche A4 · 1 page', mod: ['docx'],
    corps: [
      B.cartes({ items: [['😊', 'La joie'], ['😢', 'La tristesse'], ['😠', 'La colère'], ['😨', 'La peur'], ['😲', 'La surprise'], ['🤢', 'Le dégoût'], ['😎', 'La fierté'], ['😳', 'La gêne']], cols: 4, h: 44 }),
      B.champs({ titre: 'Quand je ressens…', items: [['La joie, c’est quand', 1], ['La colère, c’est quand', 1], ['La peur, c’est quand', 1], ['La fierté, c’est quand', 1]], cols: 2 }),
      B.texte('Toutes les émotions sont permises ; ce sont les gestes qui ont des règles. On ne corrige pas une émotion, on l’accueille et on aide à trouver quoi en faire.', true),
    ],
  },
  {
    ...base,
    id: 'cartes-j-ai-besoin',
    titre: '12 cartes « j’ai besoin »',
    description: 'Pause, aide, boire, toilettes, calme, bouger, parler : des cartes à montrer quand les mots ne viennent pas.',
    publics: ['petite-enfance', 'enfants', 'ados', 'adultes'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Communication · demander',
    t1: 'J’ai', t2: 'besoin de…', sous: 'je montre la carte',
    format: 'Planche A4 · 1 page', mod: ['docx'],
    corps: [
      B.bandeau('<b>Mode d’emploi :</b> chaque carte montrée est une vraie demande : on y répond, ou on dit quand on pourra y répondre. Une carte qui n’obtient jamais rien cesse d’être utilisée.'),
      B.cartes({ items: [['⏸️', 'Une pause'], ['🙋', 'De l’aide'], ['🥤', 'Boire'], ['🚽', 'Les toilettes'], ['🤫', 'Du calme'], ['🏃', 'Bouger'], ['🗣️', 'Parler à quelqu’un'], ['🍎', 'Manger'], ['🎧', 'Moins de bruit'], ['❓', 'Je ne comprends pas'], ['✋', 'Arrêter'], ['✏️', '']], cols: 4, h: 44 }),
    ],
  },
  {
    ...base,
    id: 'carte-pause',
    titre: 'Carte pause à garder sur soi',
    description: 'Quatre cartes pause au format portefeuille, et la règle d’usage à afficher : quand, où, combien de temps, et comment on revient.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Émotions · prendre une pause',
    t1: 'Ma carte', t2: 'pause', sous: 'je sors avant d’exploser',
    format: 'Planche A4 · 1 page', mod: ['docx'],
    corps: [
      B.cartes({ items: [['⏸️', 'PAUSE · je reviens dans 5 minutes'], ['⏸️', 'PAUSE · je reviens dans 5 minutes'], ['⏸️', 'PAUSE · je reviens dans 5 minutes'], ['⏸️', 'PAUSE · je reviens dans 5 minutes']], cols: 2, h: 52 }),
      B.champs({ titre: 'La règle de ma carte pause', items: [['Je peux l’utiliser quand', 1], ['Je vais (le lieu)', 1], ['Pendant (la durée)', 1], ['Pour revenir, je', 1]], cols: 2, couleur: 'indigo' }),
      B.texte('La carte se négocie à froid et elle s’accorde sans discussion sur le moment : une pause refusée apprend que la carte ne sert à rien.', true),
    ],
  },
  {
    ...base,
    id: 'tableau-de-communication-de-base',
    titre: 'Tableau de communication de base',
    description: 'Oui, non, encore, fini, aide, je veux, j’ai mal : seize cases à montrer du doigt, et des cases vierges pour les mots de la personne.',
    publics: ['petite-enfance', 'enfants', 'adultes'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Communication · montrer du doigt',
    t1: 'Mon tableau', t2: 'pour dire', sous: 'je montre, on me répond',
    format: 'Support A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.cartes({ items: [['👍', 'Oui'], ['👎', 'Non'], ['🔁', 'Encore'], ['🏁', 'Fini'], ['🙋', 'Aide'], ['👉', 'Je veux'], ['🤕', 'J’ai mal'], ['⏸️', 'Pause'], ['🍽️', 'Manger'], ['🥤', 'Boire'], ['🚽', 'Toilettes'], ['🏠', 'Maison'], ['✏️', ''], ['✏️', ''], ['✏️', ''], ['✏️', '']], cols: 4, h: 40 }),
      B.texte('Ce tableau ne remplace pas un outil de communication choisi avec l’équipe et la famille. Il ne se retire jamais, à aucun moment et pour aucune raison.', true),
    ],
  },
  {
    ...base,
    id: 'ma-boite-a-calme',
    titre: 'Ma boîte à calme',
    description: 'Six outils pour redescendre, choisis par la personne, et la liste de ce qu’on met dans une vraie boîte à garder à portée.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Émotions · redescendre',
    t1: 'Ma boîte', t2: 'à calme', sous: 'six outils qui m’aident',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.cartes({ titre: 'Mes six outils, dessinés ou écrits', items: [], vides: 6, cols: 3, h: 48 }),
      B.puces('Idées à essayer ensemble', ['Respirer en comptant jusqu’à quatre, trois fois.', 'Serrer une balle, un coussin, ou ses propres mains.', 'Boire un verre d’eau fraîche.', 'Écouter une musique choisie, avec un casque.', 'Regarder un livre ou des photos qu’on aime.', 'S’asseoir dans un coin calme, sans qu’on parle.'], 'vert'),
      B.texte('Ce qui calme l’un agace l’autre : on teste, on garde ce qui marche pour cette personne-là.', true),
    ],
  },
  {
    ...base,
    id: 'cartes-emotions-a-mimer',
    titre: '16 cartes émotions pour jouer',
    description: 'Seize cartes à tirer au sort pour mimer, raconter ou deviner une émotion, en groupe, dès 5 ans.',
    publics: ['enfants', 'ados'],
    metiers: ['education', 'animation', 'protection', 'handicap'],
    kicker: 'Émotions · jeu de groupe',
    t1: '16 cartes', t2: 'à mimer', sous: 'je tire, je mime, on devine',
    format: 'Planche A4 · 1 page', mod: ['docx'],
    corps: [
      B.bandeau('<b>Règle du jeu :</b> un joueur tire une carte et mime l’émotion sans parler. Les autres devinent, puis chacun peut raconter une fois où il l’a ressentie. Personne n’est obligé de raconter.'),
      B.cartes({ items: [['😊', 'Content'], ['😢', 'Triste'], ['😠', 'En colère'], ['😨', 'Effrayé'], ['😲', 'Surpris'], ['🤢', 'Dégoûté'], ['😎', 'Fier'], ['😳', 'Gêné'], ['😴', 'Fatigué'], ['🤩', 'Émerveillé'], ['😟', 'Inquiet'], ['😤', 'Énervé'], ['🥰', 'Aimé'], ['😕', 'Déçu'], ['😌', 'Soulagé'], ['🤔', 'Pensif']], cols: 4, h: 38 }),
    ],
    lex: { outil: 'groupe', libelle: 'Préparer une séance émotions avec LEX', valeurs: { objectif: 'reconnaître et nommer les émotions', public: '8 enfants de 6 à 9 ans', duree: '30 minutes' } },
  },
  {
    ...base,
    id: 'mon-niveau-d-energie',
    titre: 'Mon niveau d’énergie',
    description: 'Une échelle de batterie en cinq niveaux pour dire, sans long discours, si on est en forme, fatigué ou à bout.',
    publics: ['enfants', 'ados', 'adultes'],
    metiers: ['education', 'handicap', 'protection', 'social'],
    kicker: 'Émotions · fatigue',
    t1: 'Mon niveau', t2: 'd’énergie', sous: 'je montre ma batterie',
    format: 'Affiche A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.echelle('', [
        ['#1f8a5b', 'Batterie pleine', 'Je peux faire une activité nouvelle ou difficile.'],
        ['#7cb342', 'Ça va', 'Je fais ce qui est prévu.'],
        ['#f4c542', 'Je fatigue', 'J’ai besoin d’une activité plus simple ou d’une pause courte.'],
        ['#f08a3c', 'Presque vide', 'J’ai besoin de calme et de moins de demandes.'],
        ['#d9454b', 'À plat', 'J’ai besoin de me reposer maintenant.'],
      ]),
      B.texte('À adapter avec la personne : ses mots, ses couleurs, ce qui l’aide à chaque niveau.', true),
    ],
  },
];
