const { B } = require('../dsl.js');
const { TOUS, ENF, CLAIR } = require('./commun.js');

const base = { cat: 'familles', theme: 'Familles', metiers: ['education', 'animation', 'protection', 'handicap', 'associatif'] };

module.exports = [
  {
    ...base,
    id: 'modele-autorisation-de-sortie',
    titre: 'Modèle : autorisation de sortie',
    description: 'L’autorisation à faire signer pour une sortie : lieu, date, horaires, transport, encadrement, personne à joindre.',
    publics: ['familles', 'equipes'],
    kicker: 'Familles · autorisation',
    t1: 'Autorisation', t2: 'de sortie', sous: 'à rendre signée avant le départ', modele: true,
    format: 'Modèle A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ titre: 'La sortie', items: [['Lieu', 1], ['Date', 1], ['Départ et retour prévus', 1], ['Transport', 1], ['Encadrement', 1], ['À prévoir (tenue, repas, argent)', 1]], cols: 2, couleur: 'indigo' }),
      B.champs({ titre: 'Autorisation', items: [['Je soussigné(e), nom et prénom', 1], ['Responsable légal de', 1]], cols: 1 }),
      B.cocher('', ['autorise mon enfant à participer à cette sortie.', 'n’autorise pas mon enfant à participer à cette sortie.']),
      B.champs({ items: [['Téléphone où me joindre le jour de la sortie', 1], ['Informations utiles (allergie, traitement, peur…)', 2]], cols: 1 }),
      B.signatures(['Date et signature du responsable légal']),
    ],
    lex: CLAIR,
  },
  {
    ...base,
    id: 'modele-autorisation-droit-a-l-image',
    titre: 'Modèle : autorisation de droit à l’image',
    description: 'Photos et vidéos : pour quels usages, quels supports, combien de temps, et le droit de retirer son accord à tout moment.',
    publics: ['familles', 'adultes', 'equipes'],
    metiers: TOUS,
    kicker: 'Familles · droit à l’image',
    t1: 'Autorisation', t2: 'droit à l’image', sous: 'usage par usage', modele: true,
    format: 'Modèle A4 · 1 page', mod: ['docx'],
    corps: [
      B.bandeau('<b>Pourquoi usage par usage :</b> accepter une photo dans le journal interne n’est pas accepter une publication sur internet. La personne choisit chaque case, et peut changer d’avis.'),
      B.champs({ items: [['Je soussigné(e)', 1], ['Pour moi-même ou pour (nom de l’enfant)', 1]], cols: 2 }),
      B.tableau({ cols: [{ t: 'Usage', w: 64 }, { t: 'J’accepte', w: 18 }, { t: 'Je refuse', w: 18 }], lignes: [['Affichage dans les locaux de la structure', '☐', '☐'], ['Journal ou document interne remis aux familles', '☐', '☐'], ['Site internet de la structure', '☐', '☐'], ['Réseaux sociaux de la structure', '☐', '☐'], ['Presse locale', '☐', '☐']], premiereGras: true, h: 10 }),
      B.champs({ items: [['Durée de l’accord (par exemple : l’année scolaire en cours)', 1]] }),
      B.texte('Aucune image ne sera utilisée à des fins commerciales ni cédée à un tiers. Vous pouvez retirer votre accord à tout moment, sur simple demande auprès de la structure ; les images concernées seront alors retirées des supports qu’elle gère.', true),
      B.signatures(['Date et signature']),
    ],
  },
  {
    ...base,
    id: 'modele-mot-d-information-aux-familles',
    titre: 'Modèle : mot d’information aux familles',
    description: 'Une demi-page claire pour annoncer un événement, un changement d’horaire ou une fermeture, en double exemplaire.',
    publics: ['familles', 'equipes'],
    kicker: 'Familles · informer',
    t1: 'Mot', t2: 'aux familles', sous: 'deux par page, à découper', modele: true,
    format: 'Modèle A4 · 2 par page', mod: ['docx'],
    corps: [1, 2].flatMap(() => [
      B.champs({ titre: 'Information aux familles', items: [['Objet', 1], ['Ce qui change ou ce qui est prévu', 3], ['Quand', 1], ['Ce que nous vous demandons', 1], ['Contact', 1]], cols: 1, couleur: 'indigo' }),
    ]),
    lex: CLAIR,
  },
  {
    ...base,
    id: 'questionnaire-de-satisfaction-familles',
    titre: 'Questionnaire de satisfaction des familles',
    description: 'Dix questions courtes avec une échelle à cocher et deux questions ouvertes : à remettre en fin d’année ou de séjour.',
    publics: ['familles'],
    metiers: TOUS,
    kicker: 'Familles · votre avis',
    t1: 'Votre avis', t2: 'nous intéresse', sous: 'cinq minutes, anonyme si vous le souhaitez',
    format: 'Questionnaire A4 · 1 page', mod: ['docx'],
    corps: [
      B.tableau({ cols: [{ t: 'Question', w: 52 }, { t: 'Très satisfait', w: 12 }, { t: 'Satisfait', w: 12 }, { t: 'Peu satisfait', w: 12 }, { t: 'Pas du tout', w: 12 }], lignes: ['L’accueil de votre enfant le matin', 'Les informations que vous recevez', 'Les activités proposées', 'Le respect du rythme de votre enfant', 'La sécurité', 'Les repas', 'La facilité à joindre l’équipe', 'La façon dont vos remarques sont prises en compte', 'Ce que votre enfant en dit à la maison', 'Votre satisfaction générale'].map((q) => [q, '☐', '☐', '☐', '☐']), h: 9 }),
      B.champs({ items: [['Ce que vous avez le plus apprécié', 2], ['Ce que nous pourrions améliorer', 2]], cols: 1 }),
    ],
  },
  {
    ...base,
    id: 'fiche-tout-sur-moi',
    titre: 'Fiche « tout sur moi » remplie avec l’enfant',
    description: 'Ce que j’aime, ce qui me fait peur, ce qui m’aide, comment je dis que ça ne va pas : la fiche qui accompagne l’enfant à son arrivée.',
    publics: ['petite-enfance', 'enfants', 'familles'],
    metiers: ['education', 'animation', 'protection', 'handicap'],
    kicker: 'Familles · arrivée',
    t1: 'Tout', t2: 'sur moi', sous: 'remplie avec moi',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.cote(B.zone('Ma photo ou mon dessin', 40), B.champs({ items: [['Je m’appelle', 1], ['J’ai … ans', 1], ['On m’appelle aussi', 1]], cols: 1 })),
      B.cote(B.champs({ titre: 'Ce que j’aime', items: [['', 3]], couleur: 'vert' }), B.champs({ titre: 'Ce que je n’aime pas', items: [['', 3]], couleur: 'corail' })),
      B.cote(B.champs({ titre: 'Ce qui me fait peur', items: [['', 2]] }), B.champs({ titre: 'Ce qui me rassure', items: [['', 2]], couleur: 'indigo' })),
      B.champs({ titre: 'Quand ça ne va pas, je…', items: [['Ce que je fais, ce que je dis, ce qui m’aide', 2]], couleur: 'jaune' }),
      B.champs({ items: [['Rempli le, avec', 1]] }),
    ],
  },
  {
    ...base,
    id: 'invitation-reunion-des-familles',
    titre: 'Invitation à la réunion des familles',
    description: 'L’invitation avec le programme de la réunion, la garde des enfants si elle est prévue, et un coupon pour s’inscrire.',
    publics: ['familles', 'equipes'],
    kicker: 'Familles · réunion',
    t1: 'Invitation', t2: 'réunion des familles', sous: 'nous serions heureux de vous voir', modele: true,
    format: 'Modèle A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Date', 1], ['Heure', 1], ['Lieu', 1], ['Durée prévue', 1]], cols: 2, couleur: 'indigo' }),
      B.champs({ titre: 'Au programme', items: [['', 4]] }),
      B.cocher('', ['Les enfants peuvent être accueillis pendant la réunion.', 'Un interprète peut être présent si vous le demandez.']),
      B.zone('Coupon à rapporter', 34, 'Nom : ______________________ ☐ je viendrai ☐ je ne pourrai pas venir · nombre de personnes : ____ · j’aimerais qu’on parle de : ______________________'),
    ],
  },
  {
    ...base,
    id: 'preparer-un-entretien-avec-une-famille',
    titre: 'Préparer un entretien avec une famille',
    description: 'Ce que je veux dire, ce que je veux comprendre, ce que la famille attend peut-être, et comment finir sur une suite claire.',
    publics: ['equipes', 'familles'],
    metiers: ['education', 'protection', 'social', 'handicap'],
    kicker: 'Familles · entretien',
    t1: 'Préparer', t2: 'un entretien', sous: 'pour qu’il serve à tout le monde',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Famille', 1], ['Date et lieu', 1], ['Présents', 1], ['Objet', 1]], cols: 2 }),
      B.cote(B.champs({ titre: 'Ce que je veux dire', items: [['Faits, points d’appui, inquiétudes', 4]], couleur: 'indigo' }), B.champs({ titre: 'Ce que je veux comprendre', items: [['Questions ouvertes à poser', 4]], couleur: 'vert' })),
      B.champs({ titre: 'Ce que la famille attend peut-être', items: [['', 2]] }),
      B.puces('Pendant l’entretien', ['Commencer par ce qui va.', 'Parler de faits, pas de jugements sur la personne.', 'Laisser la famille parler sans l’interrompre, reformuler.', 'Finir sur une décision ou une prochaine date.']),
      B.champs({ titre: 'Ce qui a été convenu', items: [['', 2]], couleur: 'jaune' }),
    ],
  },
  {
    ...base,
    id: 'transmission-de-la-journee-petite-enfance',
    titre: 'Transmission de la journée en petite enfance',
    description: 'Repas, sieste, changes, humeur, activités et petit mot : la fiche du soir à remettre aux parents, deux enfants par page.',
    publics: ['petite-enfance', 'familles'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Petite enfance · transmission',
    t1: 'Ma journée', t2: 'à la crèche', sous: 'ce que les parents veulent savoir',
    format: 'Fiche A4 · 2 par page', mod: ['docx'],
    corps: [1, 2].flatMap(() => [
      B.champs({ items: [['Enfant', 1], ['Date', 1]], cols: 2, couleur: 'indigo' }),
      B.tableau({ cols: [{ t: 'Repas', w: 25 }, { t: 'Sieste', w: 25 }, { t: 'Changes', w: 25 }, { t: 'Humeur', w: 25 }], vides: 1, h: 18 }),
      B.champs({ items: [['Ce que j’ai fait aujourd’hui, un petit mot', 2]] }),
    ]),
  },
  {
    ...base,
    id: 'planning-d-adaptation',
    titre: 'Planning d’adaptation d’un nouvel enfant',
    description: 'Les premiers jours, de la visite avec le parent à la journée complète : durée, présence du parent, ce qu’on observe et ce qu’on se dit.',
    publics: ['petite-enfance', 'enfants', 'familles'],
    metiers: ['education', 'handicap', 'animation', 'protection'],
    kicker: 'Accueil · adaptation',
    t1: 'Planning', t2: 'd’adaptation', sous: 'à son rythme, construit avec les parents',
    format: 'Tableau A4 · 1 page', mod: ['docx', 'xlsx'],
    corps: [
      B.champs({ items: [['Enfant', 1], ['Professionnel référent', 1]], cols: 2 }),
      B.tableau({ feuille: 'Adaptation', cols: [{ t: 'Jour', w: 12 }, { t: 'Durée', w: 14 }, { t: 'Le parent est', w: 20 }, { t: 'Ce qu’on observe', w: 30 }, { t: 'Ce qu’on se dit', w: 24 }], lignes: [['Jour 1', '1 h', 'présent', '', ''], ['Jour 2', '1 h', 'présent puis part', '', ''], ['Jour 3', '2 h', 'absent', '', ''], ['Jour 4', 'avec un repas', 'absent', '', ''], ['Jour 5', 'avec la sieste', 'absent', '', ''], ['Jour 6', 'journée', 'absent', '', '']], premiereGras: true, h: 18 }),
      B.texte('Ces durées sont un exemple : le rythme se décide avec les parents et s’ajuste à ce que montre l’enfant.', true),
    ],
  },
];
