const { B } = require('../dsl.js');
const { ENF, EDUC, JOURS, JOURS5, ADAPTER, OBJECTIFS } = require('./commun.js');

const base = { cat: 'motivation', theme: 'Motivation', metiers: ENF };

const GARDE = 'On ne retire jamais un point gagné, et on ne conditionne jamais un besoin fondamental : repas, sommeil, soins, lien avec la famille, moyen de communication.';

const diplome = (emo, gros, phrase) => [
  `<div class="diplome"><div class="emo">${emo}</div><div class="gros">${gros}</div><div class="main">est décerné à</div><div class="ligne-nom"></div><div style="font-size:13pt;max-width:75%">${phrase}</div><div class="main">le ____ / ____ / ________</div><div style="display:flex;gap:30mm;margin-top:6mm;font-size:9pt;color:#5b6275"><span>Signature de l’adulte</span><span>Signature de l’enfant</span></div></div>`,
];

module.exports = [
  {
    ...base,
    id: 'tableau-motivation-semaine',
    titre: 'Tableau de motivation de la semaine',
    description: 'Un objectif à la fois, une case par jour et par moment, et ce qu’on fête en fin de semaine, choisi avec l’enfant.',
    publics: ['enfants', 'ados'],
    kicker: 'Motivation · semaine',
    t1: 'Mon tableau', t2: 'de la semaine', sous: 'un objectif, pas dix',
    format: 'Tableau A4 paysage · 1 page', mod: ['docx', 'xlsx'], paysage: true,
    corps: [
      B.champs({ items: [['Mon objectif de la semaine, en une phrase', 1], ['Ce que je choisis si je réussis', 1]], cols: 2 }),
      B.tableau({ cols: [{ t: '', w: 16 }, ...JOURS.map((j) => ({ t: j, w: 12 }))], lignes: ['Matin', 'Midi', 'Après-midi', 'Soir'].map((m) => [m, '', '', '', '', '', '', '']), premiereGras: true, h: 18 }),
      B.cote(B.puces('Comment on remplit', ['Une gommette ou un dessin quand l’objectif est atteint.', 'Une case vide n’est pas une punition : on recommence au moment suivant.', 'Le bilan du vendredi se fait avec l’enfant, à partir de ce qui a marché.']), B.texte(GARDE, true)),
    ],
    lex: OBJECTIFS,
  },
  {
    ...base,
    id: 'tableau-a-jetons-5',
    titre: 'Tableau à jetons : 5 cases',
    description: 'Cinq jetons à gagner avant le moment choisi : le format court pour les plus jeunes ou pour démarrer.',
    publics: ['petite-enfance', 'enfants'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Motivation · tableau à jetons',
    t1: 'Je gagne', t2: '5 jetons', sous: 'et je choisis mon moment',
    format: 'Support A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.cartes({ titre: 'Je travaille pour', items: [], vides: 1, cols: 1, h: 55 }),
      B.cartes({ titre: 'Mes jetons', items: [], vides: 5, cols: 5, h: 40 }),
      B.puces('Pour l’adulte', ['Le moment choisi est décidé AVANT, avec l’enfant, et il est tenu.', 'Un jeton se donne tout de suite, avec une phrase qui dit pourquoi.', 'On commence facile : les premiers jetons doivent arriver vite.', GARDE]),
    ],
    lex: ADAPTER,
  },
  {
    ...base,
    id: 'tableau-a-jetons-10',
    titre: 'Tableau à jetons : 10 cases',
    description: 'La version à dix jetons, quand le tableau à cinq marche et qu’on peut allonger l’effort.',
    publics: ['enfants', 'ados'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Motivation · tableau à jetons',
    t1: 'Je gagne', t2: '10 jetons', sous: 'quand cinq, c’est déjà facile',
    format: 'Support A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.cartes({ titre: 'Je travaille pour', items: [], vides: 1, cols: 1, h: 45 }),
      B.cartes({ titre: 'Mes jetons', items: [], vides: 10, cols: 5, h: 34 }),
      B.puces('Pour l’adulte', ['On passe de 5 à 10 jetons seulement quand le tableau à 5 réussit presque à chaque fois.', 'Si l’enfant décroche, on revient à 5 : ce n’est pas un échec, c’est un réglage.', GARDE]),
    ],
  },
  {
    ...base,
    id: 'diplomes-de-reussite-enfants',
    titre: 'Quatre diplômes de réussite pour les enfants',
    description: 'Bravo, entraide, persévérance et premier jour : quatre diplômes à remettre au groupe ou à un enfant, avec la phrase qui dit pourquoi.',
    publics: ['petite-enfance', 'enfants'],
    metiers: ['education', 'animation', 'protection', 'handicap'],
    kicker: 'Motivation · à remettre',
    t1: 'Diplômes', t2: 'de réussite', sous: 'pour fêter ce qui a été fait',
    format: 'Diplômes A4 · 4 pages', mod: ['docx'],
    pages: [
      diplome('🏆', 'Diplôme du bravo', 'pour ce qu’il ou elle a réussi aujourd’hui : ________________________________'),
      diplome('🤝', 'Diplôme de l’entraide', 'pour avoir aidé quelqu’un du groupe : ________________________________'),
      diplome('🌱', 'Diplôme de la persévérance', 'pour avoir continué même quand c’était difficile : ________________________________'),
      diplome('⭐', 'Diplôme du premier jour', 'pour sa première journée avec nous. Bienvenue !'),
    ],
    officeCorps: [
      B.texte('<b>Diplôme du bravo</b> est décerné à ____________________ pour ce qu’il ou elle a réussi aujourd’hui : ____________________'),
      B.signatures(['Signature de l’adulte', 'Signature de l’enfant']),
      B.saut(),
      B.texte('<b>Diplôme de l’entraide</b> est décerné à ____________________ pour avoir aidé quelqu’un du groupe : ____________________'),
      B.signatures(['Signature de l’adulte', 'Signature de l’enfant']),
      B.saut(),
      B.texte('<b>Diplôme de la persévérance</b> est décerné à ____________________ pour avoir continué même quand c’était difficile : ____________________'),
      B.signatures(['Signature de l’adulte', 'Signature de l’enfant']),
      B.saut(),
      B.texte('<b>Diplôme du premier jour</b> est décerné à ____________________ pour sa première journée avec nous. Bienvenue !'),
      B.signatures(['Signature de l’adulte', 'Signature de l’enfant']),
    ],
  },
  {
    ...base,
    id: 'cartes-encouragement',
    titre: '12 cartes d’encouragement à glisser',
    description: 'Douze petites cartes qui disent précisément ce qui a été bien fait, à glisser dans un cahier ou à remettre en main propre.',
    publics: ['enfants', 'ados'],
    metiers: ['education', 'animation', 'protection', 'handicap'],
    kicker: 'Motivation · à découper',
    t1: '12 cartes', t2: 'd’encouragement', sous: 'dire précisément ce qui va',
    format: 'Planche A4 · 1 page', mod: ['docx'],
    corps: [
      B.bandeau('<b>Pourquoi ça marche :</b> « bravo » tout seul s’oublie ; « tu as attendu ton tour sans qu’on te le rappelle » se retient. Chaque carte nomme un geste précis, et une ligne reste pour l’écrire à la main.'),
      B.cartes({ items: [['👏', 'Tu as attendu ton tour'], ['🤝', 'Tu as aidé un camarade'], ['💪', 'Tu as continué jusqu’au bout'], ['🙋', 'Tu as demandé de l’aide'], ['🧹', 'Tu as rangé sans qu’on te le dise'], ['😌', 'Tu t’es calmé tout seul'], ['🗣️', 'Tu as dit ce que tu ressentais'], ['🎯', 'Tu as essayé quelque chose de nouveau'], ['👂', 'Tu as écouté jusqu’au bout'], ['⏰', 'Tu étais prêt à l’heure'], ['🌟', 'Tu as fait un effort aujourd’hui'], ['✏️', '']], cols: 4, h: 44 }),
    ],
  },
  {
    ...base,
    id: 'contrat-d-engagement',
    titre: 'Contrat d’engagement jeune et adulte',
    description: 'Un objectif choisi avec le jeune, ce que chacun s’engage à faire, la date du point et ce qu’on fera si ça ne marche pas.',
    publics: ['ados', 'adultes'],
    metiers: ['education', 'protection', 'social', 'animation'],
    kicker: 'Motivation · s’engager à deux',
    t1: 'Notre contrat', t2: 'd’engagement', sous: 'deux signatures, deux engagements',
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Le jeune', 1], ['L’adulte référent', 1]], cols: 2 }),
      B.champs({ titre: 'Ce que je veux réussir', items: [['En une phrase, avec mes mots', 2], ['Comment on saura que c’est réussi (ce qu’on pourra voir ou compter)', 2]], couleur: 'indigo' }),
      B.cote(B.champs({ titre: 'Ce que je fais', items: [['', 4]] }), B.champs({ titre: 'Ce que l’adulte fait pour m’aider', items: [['', 4]] })),
      B.champs({ items: [['Ce qu’on fait si c’est difficile', 2], ['Date du point ensemble', 1]], cols: 1 }),
      B.signatures(['Signature du jeune', 'Signature de l’adulte']),
      B.texte('Un contrat se renégocie : s’il ne tient pas, on regarde ce qui manquait (l’aide, le délai, l’objectif trop grand), pas la volonté du jeune.', true),
    ],
    lex: OBJECTIFS,
  },
  {
    ...base,
    id: 'inventaire-de-ce-qui-motive',
    titre: 'Inventaire de ce qui motive la personne',
    description: 'Activités, objets, moments partagés, ce qu’elle n’aime pas : une liste à remplir avec la personne, pas à sa place.',
    publics: ['enfants', 'ados', 'adultes'],
    metiers: EDUC,
    kicker: 'Motivation · connaître la personne',
    t1: 'Ce qui me fait', t2: 'plaisir', sous: 'rempli avec moi, pas à ma place',
    format: 'Trame A4 · 1 page', mod: ['docx'],
    corps: [
      B.bandeau('<b>Mode d’emploi :</b> remplissez ce document avec la personne, en lui montrant des objets ou des images si besoin. Ce qui motive change : on le relit tous les deux mois.'),
      B.cote(B.champs({ titre: 'Les activités que j’aime', items: [['', 4]], couleur: 'vert' }), B.champs({ titre: 'Les objets que j’aime', items: [['', 4]], couleur: 'vert' })),
      B.cote(B.champs({ titre: 'Les moments partagés que j’aime', items: [['', 4]], couleur: 'indigo' }), B.champs({ titre: 'Ce que j’aime entendre', items: [['', 4]], couleur: 'indigo' })),
      B.champs({ titre: 'Ce que je n’aime pas, ou qui me gêne', items: [['Félicitations en public, contact, bruit… à noter ici', 3]], couleur: 'corail' }),
      B.champs({ items: [['Rempli le', 1], ['Avec', 1]], cols: 2 }),
    ],
  },
  {
    ...base,
    id: 'objectif-de-la-semaine',
    titre: 'Mon objectif de la semaine',
    description: 'Une page pour un seul objectif : ce que je vais faire, comment je saurai que j’ai réussi, et ce que je retiens vendredi.',
    publics: ['enfants', 'ados', 'adultes'],
    metiers: ['education', 'protection', 'handicap', 'social', 'animation'],
    kicker: 'Motivation · une semaine, un objectif',
    t1: 'Mon objectif', t2: 'de la semaine', sous: 'un seul, mais tenu',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ titre: 'Mon objectif', items: [['Je vais…', 2], ['Je saurai que j’ai réussi quand…', 2]], couleur: 'indigo' }),
      B.tableau({ titre: 'Chaque jour', cols: [{ t: 'Jour', w: 18 }, { t: 'Je l’ai fait ?', w: 18 }, { t: 'Ce qui m’a aidé, ou ce qui a gêné', w: 64 }], lignes: JOURS5.map((j) => [j, '', '']), premiereGras: true, h: 14 }),
      B.champs({ titre: 'Vendredi, je retiens', items: [['Ce qui a marché', 2], ['Ce que je garde pour la semaine prochaine', 2]], couleur: 'vert' }),
    ],
    lex: OBJECTIFS,
  },
];
