const { B } = require('../dsl.js');
const { TOUS, EDUC, ENF, JOURS5, FACTUEL, OBJECTIFS } = require('./commun.js');

const base = { cat: 'observation', theme: 'Observer', metiers: EDUC };

module.exports = [
  {
    ...base,
    id: 'grille-abc-avant-pendant-apres',
    titre: 'Grille ABC : avant, comportement, après',
    description: 'Ce qui s’est passé juste avant, ce que la personne a fait, ce qui a suivi : huit lignes pour repérer ce qui revient.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Observer · comprendre un comportement',
    t1: 'Grille', t2: 'avant, pendant, après', sous: 'des faits, rien que des faits',
    format: 'Grille A4 paysage · 1 page', mod: ['docx', 'xlsx'], paysage: true,
    corps: [
      B.bandeau('<b>Le test de la caméra :</b> une caméra aurait-elle filmé ce que vous écrivez ? « Il a jeté sa chaise » oui ; « il voulait provoquer » non. Les hypothèses vont dans la dernière colonne, et seulement là.'),
      B.tableau({ cols: [{ t: 'Date, heure, lieu', w: 13 }, { t: 'Juste avant (qui, quoi, quelle demande)', w: 24 }, { t: 'Ce que la personne a fait', w: 24 }, { t: 'Juste après (ce qu’ont fait les adultes)', w: 24 }, { t: 'Hypothèse', w: 15 }], vides: 8, h: 12 }),
    ],
    lex: FACTUEL,
  },
  {
    ...base,
    id: 'releve-de-frequence',
    titre: 'Relevé de fréquence sur deux semaines',
    description: 'Combien de fois, à quel moment de la journée : la ligne de base qu’on prend avant de changer quoi que ce soit.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Observer · compter',
    t1: 'Relevé', t2: 'de fréquence', sous: 'compter avant d’agir',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.champs({ items: [['Le comportement observé, décrit pour que deux collègues comptent la même chose', 1]], cols: 1 }),
      B.tableau({ feuille: 'Relevé', cols: [{ t: 'Moment', w: 16 }, ...['L', 'M', 'M', 'J', 'V', 'L', 'M', 'M', 'J', 'V'].map((j, i) => ({ t: `${j}${i < 5 ? ' s1' : ' s2'}`, w: 8.4 }))], lignes: ['Arrivée', 'Matinée', 'Repas', 'Après-midi', 'Fin de journée', 'Total du jour'].map((m) => [m, '', '', '', '', '', '', '', '', '', '']), premiereGras: true, h: 14 }),
      B.texte('Une barre par fois. On compare la semaine 1 et la semaine 2 avant de conclure : un seul jour difficile ne dit rien.', true),
    ],
  },
  {
    ...base,
    id: 'grille-de-participation-atelier',
    titre: 'Grille de participation à un atelier',
    description: 'Douze participants, dix séances : présence et participation en codes simples, pour un bilan fondé sur des chiffres réels.',
    publics: ['enfants', 'ados', 'adultes', 'equipes'],
    metiers: TOUS,
    kicker: 'Observer · suivre un groupe',
    t1: 'Grille', t2: 'de participation', sous: 'P présent · A absent · ★ très investi',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.champs({ items: [['Atelier', 1], ['Animé par', 1]], cols: 2 }),
      B.tableau({ feuille: 'Participation', cols: [{ t: 'Participant', w: 20 }, ...Array.from({ length: 10 }, (_, i) => ({ t: `S${i + 1}`, w: 7 })), { t: 'Total', w: 10 }], vides: 12, h: 7, ligneFormule: [11, '=COUNTIF(B{r}:K{r},"P")+COUNTIF(B{r}:K{r},"★")'] }),
      B.texte('Codes proposés : P présent, A absent, E excusé, ★ très investi. Gardez les mêmes codes du début à la fin.', true),
    ],
    lex: { outil: 'bilan', libelle: 'Préparer mon bilan avec LEX' },
  },
  {
    ...base,
    id: 'evaluation-d-une-activite',
    titre: 'Évaluer une activité après coup',
    description: 'Prévu et réalisé, ce qui a marché, ce qui a coincé, ce qu’on garde : la fiche à remplir dans les dix minutes qui suivent.',
    publics: ['equipes'],
    metiers: TOUS,
    kicker: 'Observer · faire le bilan',
    t1: 'Bilan', t2: 'd’une activité', sous: 'dix minutes, juste après',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Activité', 1], ['Date et durée réelle', 1], ['Participants prévus / présents', 1], ['Encadrants', 1]], cols: 2 }),
      B.cote(B.champs({ titre: 'Ce qui était prévu', items: [['Objectifs', 3]] }), B.champs({ titre: 'Ce qui s’est passé', items: [['Faits observés', 3]] })),
      B.cote(B.champs({ titre: 'Ce qui a marché', items: [['', 3]], couleur: 'vert' }), B.champs({ titre: 'Ce qui a coincé', items: [['', 3]], couleur: 'corail' })),
      B.champs({ titre: 'La prochaine fois', items: [['Ce qu’on garde, ce qu’on change', 2]], couleur: 'indigo' }),
    ],
    lex: { outil: 'intervention', libelle: 'Transformer mes notes en compte rendu avec LEX' },
  },
  {
    ...base,
    id: 'grille-d-autonomie-au-quotidien',
    titre: 'Grille d’autonomie au quotidien',
    description: 'Douze gestes du quotidien, et pour chacun le niveau d’aide réel : seul, avec un rappel, avec un geste, fait avec l’adulte.',
    publics: ['enfants', 'ados', 'adultes'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Observer · autonomie',
    t1: 'Grille', t2: 'd’autonomie', sous: 'ce que la personne fait, aujourd’hui',
    format: 'Grille A4 · 1 page', mod: ['xlsx', 'docx'],
    corps: [
      B.tableau({ feuille: 'Autonomie', cols: [{ t: 'Geste', w: 34 }, { t: 'Seul', w: 11 }, { t: 'Avec un rappel', w: 13 }, { t: 'Avec un geste', w: 13 }, { t: 'Fait avec l’adulte', w: 13 }, { t: 'Remarque', w: 16 }], lignes: ['Se laver les mains', 'S’habiller', 'Se brosser les dents', 'Mettre la table', 'Manger seul', 'Ranger ses affaires', 'Préparer son sac', 'Aller aux toilettes', 'Se repérer dans les lieux', 'Utiliser le téléphone', 'Gérer un peu d’argent', 'Prendre les transports'].map((g) => [g, '', '', '', '', '']), h: 12 }),
      B.champs({ items: [['Observé du … au …', 1], ['Par', 1]], cols: 2 }),
      B.texte('On coche le niveau observé plusieurs fois, pas celui qu’on espère. Ce relevé sert à choisir le prochain geste à travailler, un seul à la fois.', true),
    ],
    lex: OBJECTIFS,
  },
  {
    ...base,
    id: 'suivi-des-objectifs',
    titre: 'Tableau de suivi des objectifs',
    description: 'Chaque objectif avec son critère observable, sa date de point et où on en est : le suivi d’un projet personnalisé sur une page.',
    publics: ['enfants', 'ados', 'adultes'],
    metiers: TOUS,
    kicker: 'Observer · suivre un projet',
    t1: 'Suivi', t2: 'des objectifs', sous: 'atteint, en cours, à revoir',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.tableau({ feuille: 'Objectifs', cols: [{ t: 'Objectif', w: 24 }, { t: 'Critère : on saura que c’est atteint quand', w: 24 }, { t: 'Moyens', w: 18 }, { t: 'Qui', w: 10 }, { t: 'Date du point', w: 10 }, { t: 'Où on en est', w: 14 }], vides: 7, h: 16 }),
      B.texte('Où on en est : atteint, en cours, à revoir. Un objectif « à revoir » n’est pas un échec de la personne : c’est l’objectif ou les moyens qu’on ajuste.', true),
    ],
    lex: OBJECTIFS,
  },
  {
    ...base,
    id: 'journal-de-bord-educatif',
    titre: 'Journal de bord de la journée',
    description: 'Une page par jour : faits marquants, ce qui a été dit, ce qui est à transmettre, en séparant les faits des impressions.',
    publics: ['equipes'],
    metiers: ['education', 'protection', 'handicap', 'animation'],
    kicker: 'Observer · au fil de la journée',
    t1: 'Journal', t2: 'de bord', sous: 'les faits d’abord',
    format: 'Fiche A4 · 1 page', mod: ['docx'],
    corps: [
      B.champs({ items: [['Date', 1], ['Rédigé par', 1]], cols: 2 }),
      B.champs({ titre: 'Faits marquants de la journée', items: [['Qui, quoi, quand, où', 5]], couleur: 'indigo' }),
      B.champs({ titre: 'Paroles rapportées', items: [['Entre guillemets, mot pour mot', 3]] }),
      B.cote(B.champs({ titre: 'Mon impression', items: [['Ce que je pense, annoncé comme tel', 3]], couleur: 'jaune' }), B.champs({ titre: 'À transmettre', items: [['À l’équipe suivante, à la famille, au cadre', 3]], couleur: 'vert' })),
    ],
    lex: { outil: 'transmission', libelle: 'Écrire ma transmission avec LEX' },
  },
  {
    ...base,
    id: 'observation-du-jeu-libre',
    titre: 'Observer un temps de jeu libre',
    description: 'Avec qui, à quoi, combien de temps, ce qui a interrompu le jeu : une grille pour voir comment un enfant joue vraiment.',
    publics: ['petite-enfance', 'enfants'],
    metiers: ['education', 'animation', 'handicap', 'protection'],
    kicker: 'Observer · le jeu',
    t1: 'Observer', t2: 'le jeu libre', sous: 'regarder sans intervenir',
    format: 'Grille A4 · 1 page', mod: ['docx', 'xlsx'],
    corps: [
      B.champs({ items: [['Enfant (prénom ou initiale)', 1], ['Date, lieu, durée de l’observation', 1]], cols: 2 }),
      B.tableau({ feuille: 'Jeu libre', cols: [{ t: 'Heure', w: 12 }, { t: 'À quoi il joue', w: 24 }, { t: 'Avec qui', w: 18 }, { t: 'Combien de temps', w: 14 }, { t: 'Ce qui a interrompu', w: 32 }], vides: 9, h: 14 }),
      B.champs({ titre: 'Ce que je retiens', items: [['', 2]], couleur: 'vert' }),
    ],
  },
];
