const { B } = require('../dsl.js');

const base = { cat: 'scenarios', theme: 'Scénario social', metiers: ['education', 'handicap', 'protection'], publics: ['petite-enfance', 'enfants', 'adultes'], mod: ['docx'] };

const NOTE = 'Un scénario se lit à froid, plusieurs jours avant la situation, puis juste avant. On remplace les images par des photos des vrais lieux et des vraies personnes dès qu’on le peut. Les phrases décrivent et rassurent ; elles n’ordonnent pas.';

const scenario = (id, titre, description, t2, sous, etapes, extra = {}) => ({
  ...base,
  id,
  titre: `Scénario social : ${titre}`,
  description,
  kicker: 'Scénario social · à lire ensemble',
  t1: 'Mon histoire', t2, sous,
  format: 'Scénario A4 · 1 page', classe: 'poster',
  corps: [B.cartes({ items: etapes, cols: 2, h: 44 }), B.texte(NOTE, true)],
  ...extra,
});

module.exports = [
  {
    ...base,
    id: 'trame-scenario-social',
    titre: 'Trame vierge de scénario social',
    description: 'Huit cases image et phrase pour écrire l’histoire d’une situation qui inquiète, avec les règles d’écriture au dos.',
    publics: ['equipes', 'familles'],
    kicker: 'Scénario social · à écrire',
    t1: 'Écrire', t2: 'un scénario social', sous: 'une situation, huit cases',
    format: 'Trame A4 · 2 pages',
    pages: [
      [B.champs({ items: [['La situation', 1], ['Pour', 1]], cols: 2 }), B.cartes({ items: [], vides: 8, cols: 2, h: 44 })],
      [
        B.puces('Les règles d’écriture', ['Écrire à la première personne et au présent : « Je vais chez le coiffeur. »', 'Décrire ce qui va se passer, dans l’ordre, avec ce qu’on voit et ce qu’on entend.', 'Dire ce que les autres pensent ou ressentent : « La coiffeuse est contente de m’aider. »', 'Proposer ce que la personne PEUT faire, sans ordre : « Je peux tenir ma balle. »', 'Prévoir ce qui peut changer : « Parfois, il faut attendre. »', 'Finir sur une phrase rassurante et vraie.'], 'indigo'),
        B.cote(B.puces('À éviter', ['« Je dois », « il faut », « je ne dois pas ».', 'Les promesses qu’on ne peut pas tenir.', 'Les images qui font peur.'], 'corail'), B.puces('Pour bien l’utiliser', ['Le lire plusieurs jours avant, à un moment calme.', 'Le relire juste avant la situation.', 'Le garder pour le relire après, et le corriger si quelque chose était différent.'], 'vert')),
      ],
    ],
    lex: { outil: 'clair', libelle: 'Rendre mon scénario plus simple avec LEX' },
  },
  scenario('scenario-social-attendre-mon-tour', 'attendre mon tour', 'Huit cases pour comprendre pourquoi on attend, ce qu’on peut faire pendant, et ce qui arrive ensuite.', 'attendre mon tour', 'je peux attendre', [
    ['👫', 'Quand on est plusieurs, on ne peut pas tous parler ou jouer en même temps.'],
    ['⏳', 'Alors chacun attend son tour.'],
    ['😕', 'Attendre, c’est parfois long. C’est normal de trouver ça difficile.'],
    ['🧸', 'Pendant que j’attends, je peux tenir un objet, compter dans ma tête ou regarder les autres.'],
    ['🙋', 'Si c’est trop long, je peux le dire à l’adulte.'],
    ['👀', 'L’adulte me montre quand c’est bientôt à moi.'],
    ['😊', 'Puis c’est mon tour !'],
    ['💛', 'Quand j’attends, les autres sont contents de jouer avec moi.'],
  ]),
  scenario('scenario-social-chez-le-medecin', 'chez le médecin', 'La salle d’attente, le bureau, ce que le médecin regarde et pourquoi : huit cases pour préparer un rendez-vous.', 'chez le médecin', 'je sais comment ça se passe', [
    ['🚗', 'Aujourd’hui, je vais chez le médecin avec un adulte.'],
    ['🪑', 'J’attends dans la salle d’attente. Il y a d’autres personnes qui attendent aussi.'],
    ['🚪', 'Le médecin m’appelle. J’entre dans son bureau avec l’adulte.'],
    ['🗣️', 'Le médecin pose des questions. L’adulte peut répondre avec moi.'],
    ['🩺', 'Le médecin peut écouter mon cœur, regarder mes oreilles ou ma gorge. Ça ne dure pas longtemps.'],
    ['✋', 'Si j’ai peur, je peux le dire ou montrer ma carte pause.'],
    ['👋', 'Quand c’est fini, je dis au revoir.'],
    ['🏠', 'Après, je rentre. J’ai fait quelque chose de difficile.'],
  ]),
  scenario('scenario-social-chez-le-coiffeur', 'chez le coiffeur', 'Le bruit des ciseaux, l’eau, la cape, le miroir : huit cases pour qu’une coupe de cheveux ne soit plus une surprise.', 'chez le coiffeur', 'ça ne fait pas mal', [
    ['💈', 'Aujourd’hui, je vais chez le coiffeur pour couper mes cheveux.'],
    ['🪑', 'Je m’assois sur un grand fauteuil devant un miroir.'],
    ['🧥', 'Le coiffeur met une cape sur mes épaules pour que les cheveux ne tombent pas sur moi.'],
    ['💧', 'Parfois, il mouille mes cheveux avec de l’eau.'],
    ['✂️', 'Les ciseaux font un petit bruit. Couper les cheveux ne fait pas mal.'],
    ['🎧', 'Si le bruit me gêne, je peux mettre mon casque ou tenir mon objet.'],
    ['🪞', 'À la fin, je regarde mes cheveux dans le miroir.'],
    ['😊', 'Le coiffeur et l’adulte sont fiers de moi.'],
  ]),
  scenario('scenario-social-quand-je-suis-en-colere', 'quand je suis en colère', 'Ce qui se passe dans mon corps, ce que je peux faire, à qui je peux le dire : huit cases à lire à froid.', 'quand je suis en colère', 'je peux me calmer', [
    ['😠', 'Parfois, je suis en colère. Tout le monde est en colère un jour.'],
    ['💓', 'Quand je suis en colère, mon cœur bat vite et mes mains se serrent.'],
    ['✋', 'Je peux m’arrêter et respirer lentement trois fois.'],
    ['⏸️', 'Je peux montrer ma carte pause et aller au coin calme.'],
    ['🗣️', 'Je peux dire à un adulte : « Je suis en colère. »'],
    ['🤝', 'L’adulte m’écoute et m’aide à trouver une solution.'],
    ['😌', 'La colère finit toujours par redescendre.'],
    ['💛', 'Après, je peux reprendre ce que je faisais.'],
  ]),
  scenario('scenario-social-un-changement-de-programme', 'quand le programme change', 'Une sortie annulée, un remplaçant, la pluie : huit cases pour accepter qu’un programme change.', 'quand ça change', 'il y a toujours une suite', [
    ['📅', 'Chaque jour, il y a un programme. Je sais ce qui va se passer.'],
    ['🌧️', 'Parfois, le programme change : la pluie, une personne absente, un imprévu.'],
    ['😟', 'Quand ça change, je peux être surpris ou déçu. C’est normal.'],
    ['🗣️', 'L’adulte me dit ce qui change et pourquoi.'],
    ['🔄', 'L’adulte me montre ce qu’on va faire à la place.'],
    ['🧸', 'Je peux tenir mon objet ou demander une pause.'],
    ['📌', 'Ce qui était prévu peut parfois revenir un autre jour.'],
    ['😊', 'Même quand ça change, la journée continue.'],
  ]),
  scenario('scenario-social-perdre-a-un-jeu', 'quand je perds à un jeu', 'Gagner, perdre, rejouer : huit cases pour les enfants qui vivent mal la défaite.', 'quand je perds', 'on joue pour s’amuser', [
    ['🎲', 'J’aime jouer avec les autres.'],
    ['🏆', 'Dans un jeu, quelqu’un gagne et quelqu’un perd.'],
    ['😢', 'Quand je perds, je peux être triste ou en colère.'],
    ['😮‍💨', 'Je peux respirer et dire : « Dommage, je rejouerai. »'],
    ['👏', 'Je peux féliciter celui qui a gagné.'],
    ['🔁', 'Une autre fois, c’est peut-être moi qui gagnerai.'],
    ['🤝', 'Les autres aiment jouer avec moi quand je reste calme.'],
    ['😊', 'Le plus important, c’est de jouer ensemble.'],
  ]),
  {
    ...base,
    id: 'sequentiel-s-habiller',
    titre: 'Séquentiel : s’habiller en 8 étapes',
    description: 'Les huit étapes de l’habillage dans l’ordre, en cartes à découper ou en bande à afficher près de l’armoire.',
    theme: 'Séquentiel',
    kicker: 'Séquentiel · vie quotidienne',
    t1: 'Je m’habille', t2: 'étape par étape', sous: 'dans le même ordre chaque jour',
    format: 'Séquentiel A4 · 1 page', classe: 'poster',
    corps: [B.cartes({ items: [['🩲', '1. Le slip ou la culotte'], ['🧦', '2. Les chaussettes'], ['👖', '3. Le pantalon'], ['👕', '4. Le tee-shirt'], ['🧥', '5. Le pull ou le gilet'], ['👟', '6. Les chaussures'], ['🪞', '7. Je me regarde'], ['👍', '8. C’est fini !']], cols: 2, h: 46 }), B.texte('On adapte l’ordre et les vêtements à la personne. On retire l’aide pas à pas : d’abord on fait avec, puis on montre, puis on laisse faire.', true)],
  },
  {
    ...base,
    id: 'sequentiel-se-brosser-les-dents',
    titre: 'Séquentiel : se brosser les dents',
    description: 'Huit étapes illustrées, à coller au-dessus du lavabo, du dentifrice au rinçage.',
    theme: 'Séquentiel',
    kicker: 'Séquentiel · hygiène',
    t1: 'Je me brosse', t2: 'les dents', sous: 'matin et soir',
    format: 'Séquentiel A4 · 1 page', classe: 'poster',
    corps: [B.cartes({ items: [['🪥', '1. Je prends ma brosse'], ['🧴', '2. Je mets un peu de dentifrice'], ['⬆️', '3. Je brosse les dents du haut'], ['⬇️', '4. Je brosse les dents du bas'], ['↔️', '5. Devant, derrière, dessus'], ['💦', '6. Je crache'], ['🚰', '7. Je rince ma brosse'], ['😁', '8. J’ai les dents propres']], cols: 2, h: 46 })],
  },
  {
    ...base,
    id: 'conversation-dessinee',
    titre: 'Conversation dessinée : revenir sur une situation',
    description: 'Six cases de bande dessinée à remplir avec la personne : ce qui s’est passé, ce que chacun a dit et pensé, ce qu’on fera la prochaine fois.',
    publics: ['enfants', 'ados', 'adultes'],
    theme: 'Comprendre une situation',
    kicker: 'Communication · après une situation',
    t1: 'On en parle', t2: 'en dessinant', sous: 'qui a dit quoi, qui pensait quoi',
    format: 'Trame A4 · 1 page',
    corps: [
      B.bandeau('<b>Mode d’emploi :</b> à froid, on dessine la scène en bonhommes simples. Une bulle ronde pour ce qui a été dit, une bulle nuage pour ce qu’on pensait. La personne dessine, l’adulte pose des questions et écrit si besoin.'),
      B.cartes({ items: [['1️⃣', 'Où étions-nous ? Qui était là ?'], ['2️⃣', 'Qu’est-ce qui s’est passé ?'], ['3️⃣', 'Qu’est-ce que j’ai dit ? Qu’est-ce que je pensais ?'], ['4️⃣', 'Qu’ont dit et pensé les autres ?'], ['5️⃣', 'Comment ça s’est fini ?'], ['6️⃣', 'La prochaine fois, je pourrai…']], cols: 2, h: 62 }),
    ],
  },
];
