const { B } = require('../dsl.js');
const { ENF, EDUC, JOURS, ADAPTER } = require('./commun.js');

const base = { cat: 'temps', theme: 'Repères de temps', metiers: ENF };

const PICTOS = [
  ['🌅', 'Se lever'], ['🚽', 'Toilettes'], ['🧼', 'Se laver'], ['👕', 'S’habiller'],
  ['🥣', 'Petit déjeuner'], ['🪥', 'Se brosser les dents'], ['🎒', 'Prendre son sac'], ['🚌', 'Bus'],
  ['🏫', 'École'], ['📚', 'Travail'], ['🍽️', 'Repas'], ['🛝', 'Récréation'],
  ['🎨', 'Atelier'], ['⚽', 'Sport'], ['🌳', 'Sortie'], ['🍎', 'Goûter'],
  ['🧸', 'Temps calme'], ['📺', 'Écran'], ['🛁', 'Bain ou douche'], ['🛏️', 'Dormir'],
  ['🚗', 'Voiture'], ['🩺', 'Rendez-vous'], ['📞', 'Appel à la famille'], ['🏠', 'Maison'],
];

module.exports = [
  {
    ...base,
    id: 'cartes-pictos-quotidien',
    titre: '24 cartes images du quotidien',
    description: 'Lever, repas, école, sortie, douche, coucher : 24 cartes image et mot à découper pour construire un emploi du temps visuel.',
    publics: ['petite-enfance', 'enfants', 'adultes'],
    kicker: 'Repères · cartes à découper',
    t1: '24 cartes', t2: 'du quotidien', sous: 'à découper et à plastifier',
    format: 'Planche A4 · 2 pages', mod: ['docx'],
    pages: [
      [B.bandeau('<b>Mode d’emploi :</b> découpez, plastifiez, collez un velcro au dos. Une carte = une étape. Remplacez l’image par une photo du lieu réel dès que vous le pouvez : c’est elle que la personne reconnaît.'), B.cartes({ items: PICTOS.slice(0, 12), cols: 4, h: 50 })],
      [B.cartes({ items: PICTOS.slice(12), cols: 4, h: 50 }), B.cartes({ titre: 'Cartes vierges pour vos propres étapes', items: [], vides: 4, cols: 4, h: 40 })],
    ],
  },
  {
    ...base,
    id: 'emploi-du-temps-visuel-journee',
    titre: 'Emploi du temps visuel de la journée',
    description: 'Une bande de huit étapes à remplir avec les cartes images, et une colonne « fini » pour retirer chaque étape faite.',
    publics: ['petite-enfance', 'enfants', 'adultes'],
    kicker: 'Repères · emploi du temps',
    t1: 'Ma journée', t2: 'étape par étape', sous: 'je regarde, je fais, je range',
    format: 'Support A4 · 1 page', mod: ['docx'],
    corps: [
      B.bandeau('<b>Mode d’emploi :</b> collez une carte par ligne, de haut en bas, dans l’ordre réel de la journée. Quand l’étape est finie, la personne décroche la carte et la pose dans la boîte « fini ».'),
      B.tableau({ cols: [{ t: 'Heure', w: 14 }, { t: 'Carte image', w: 30 }, { t: 'Ce qu’on fait', w: 42 }, { t: 'Fini', w: 14 }], vides: 8, h: 18 }),
      B.zone('Boîte « fini »', 20, 'Une enveloppe collée ici, ou un bac à côté du support.'),
    ],
  },
  {
    ...base,
    id: 'semainier-visuel',
    titre: 'Semainier visuel',
    description: 'La semaine en un coup d’œil : sept jours, quatre moments, une case pour l’activité ou la personne qu’on va voir.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Repères · semaine',
    t1: 'Ma semaine', t2: 'en un coup d’œil', sous: 'matin, midi, après-midi, soir',
    format: 'Tableau A4 paysage · 1 page', mod: ['docx', 'xlsx'], paysage: true,
    corps: [
      B.tableau({ cols: [{ t: '', w: 12 }, ...JOURS.map((j) => ({ t: j, w: 12.5 }))], lignes: ['Matin', 'Midi', 'Après-midi', 'Soir'].map((m) => [m, '', '', '', '', '', '', '']), premiereGras: true, h: 24 }),
      B.cote(B.champs({ titre: 'Cette semaine, je vais voir', items: [['', 2]] }), B.champs({ titre: 'Ce qui change cette semaine', items: [['', 2]] })),
    ],
  },
  {
    ...base,
    id: 'd-abord-ensuite',
    titre: 'Tableau « d’abord, ensuite »',
    description: 'Deux cases seulement : ce qu’on fait d’abord, ce qui vient ensuite. Le support le plus simple pour démarrer une tâche.',
    publics: ['petite-enfance', 'enfants', 'adultes'],
    metiers: ['education', 'handicap', 'protection'],
    kicker: 'Repères · enchaîner deux étapes',
    t1: 'D’abord,', t2: 'ensuite', sous: 'deux cases, pas plus',
    format: 'Support A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.bandeau('<b>Mode d’emploi :</b> à gauche la tâche demandée, à droite ce qui vient après (souvent un moment apprécié). On montre, on dit en peu de mots, on tient parole sur la case de droite.'),
      B.cartes({ items: [['1️⃣', 'D’abord'], ['2️⃣', 'Ensuite']], cols: 2, h: 120 }),
      B.texte('Ce que la case de droite n’est jamais : un besoin fondamental (repas, sommeil, lien avec la famille, moyen de communication). Ce sont des droits, pas des récompenses.', true),
    ],
  },
  {
    ...base,
    id: 'routine-du-matin',
    titre: 'Routine du matin à cocher',
    description: 'Huit étapes du lever au départ, avec image et case à cocher, et deux lignes pour les étapes propres à la maison ou au foyer.',
    publics: ['enfants', 'ados'],
    kicker: 'Repères · routine',
    t1: 'Ma routine', t2: 'du matin', sous: 'je fais, je coche',
    format: 'Affiche A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.tableau({ cols: [{ t: '', w: 14 }, { t: 'Étape', w: 52 }, ...['L', 'M', 'M', 'J', 'V'].map((j) => ({ t: j, w: 6.8 }))], emo: true, lignes: [['🌅', 'Je me lève'], ['🚽', 'Je vais aux toilettes'], ['🧼', 'Je me lave'], ['👕', 'Je m’habille'], ['🥣', 'Je prends mon petit déjeuner'], ['🪥', 'Je me brosse les dents'], ['🎒', 'Je prends mon sac'], ['👟', 'Je mets mes chaussures et mon manteau']].map((l) => [...l, '', '', '', '', '']), h: 16 }),
      B.tableau({ titre: 'Mes étapes en plus', cols: [{ t: '', w: 14 }, { t: 'Étape', w: 52 }, ...['L', 'M', 'M', 'J', 'V'].map((j) => ({ t: j, w: 6.8 }))], vides: 2, h: 14 }),
    ],
  },
  {
    ...base,
    id: 'routine-du-soir',
    titre: 'Routine du soir à cocher',
    description: 'Du goûter au coucher en huit étapes illustrées, pour que la soirée se déroule toujours dans le même ordre.',
    publics: ['enfants', 'ados'],
    kicker: 'Repères · routine',
    t1: 'Ma routine', t2: 'du soir', sous: 'toujours dans le même ordre',
    format: 'Affiche A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.tableau({ cols: [{ t: '', w: 14 }, { t: 'Étape', w: 52 }, ...['L', 'M', 'M', 'J', 'V'].map((j) => ({ t: j, w: 6.8 }))], emo: true, lignes: [['🍎', 'Je prends mon goûter'], ['📚', 'Je fais mes devoirs ou je lis'], ['🧸', 'Temps libre'], ['🍽️', 'Je dîne'], ['🛁', 'Je prends ma douche'], ['🪥', 'Je me brosse les dents'], ['🎒', 'Je prépare mon sac pour demain'], ['🛏️', 'Je me couche']].map((l) => [...l, '', '', '', '', '']), h: 16 }),
      B.champs({ titre: 'Ce qui m’aide à m’endormir', items: [['', 2]] }),
    ],
  },
  {
    ...base,
    id: 'calendrier-du-mois',
    titre: 'Calendrier du mois à compléter',
    description: 'Une grille mensuelle vierge pour les rendez-vous, les visites, les sorties et les anniversaires, à afficher dans le groupe.',
    publics: ['enfants', 'ados', 'adultes', 'equipes'],
    metiers: ['education', 'animation', 'protection', 'handicap', 'social', 'associatif'],
    kicker: 'Repères · mois',
    t1: 'Le calendrier', t2: 'du mois', sous: 'rendez-vous, visites, sorties',
    format: 'Tableau A4 paysage · 1 page', mod: ['xlsx', 'docx'], paysage: true,
    corps: [
      B.tableau({ cols: JOURS.map((j) => ({ t: j, w: 14.28 })), vides: 6, h: 15 }),
      B.cote(B.puces('Légende proposée', ['🩺 rendez-vous · 👨‍👩‍👧 visite ou appel de la famille', '🌳 sortie · 🎂 anniversaire']), B.champs({ titre: 'Mois et année · à ne pas oublier', items: [['', 1]] })),
    ],
  },
  {
    ...base,
    id: 'compte-a-rebours',
    titre: 'Compte à rebours avant un événement',
    description: 'Dix cases à barrer, une par jour, avant un départ en séjour, un retour en famille ou un changement de lieu.',
    publics: ['enfants', 'ados', 'adultes'],
    kicker: 'Repères · attendre',
    t1: 'Encore', t2: 'combien de jours ?', sous: 'je barre une case chaque soir',
    format: 'Affiche A4 · 1 page', mod: ['docx'], classe: 'poster',
    corps: [
      B.champs({ items: [['Le grand jour', 1], ['Ce qui va se passer', 2]], cols: 1 }),
      B.cartes({ items: ['10', '9', '8', '7', '6', '5', '4', '3', '2', '1'].map((n) => ['', n]), cols: 5, h: 42 }),
      B.cartes({ items: [['🎉', 'C’est aujourd’hui !']], cols: 1, h: 40 }),
      B.texte('Un changement annoncé se prépare aussi en parole : on montre des photos du lieu, on dit qui sera là, on répond aux questions autant de fois qu’il le faut.', true),
    ],
  },
  {
    ...base,
    id: 'minuteur-visuel-a-colorier',
    titre: 'Minuteur visuel à colorier',
    description: 'Quatre cadrans de 5, 10, 15 et 30 minutes à colorier puis à effacer : le temps qui reste devient visible.',
    publics: ['petite-enfance', 'enfants', 'adultes'],
    metiers: ['education', 'handicap', 'animation', 'protection'],
    kicker: 'Repères · le temps qui reste',
    t1: 'Combien', t2: 'de temps il reste ?', sous: 'je colorie, puis j’efface',
    format: 'Support A4 · 1 page', mod: ['docx'],
    officeCorps: [B.bandeau('<b>Mode d’emploi :</b> plastifiez la feuille. Coloriez au feutre effaçable la part du cadran qui correspond à la durée, puis effacez une part à chaque fois que le temps avance.'), B.zone('5 minutes', 60), B.zone('10 minutes', 60), B.zone('15 minutes', 60), B.zone('30 minutes', 60)],
    corps: [
      B.bandeau('<b>Mode d’emploi :</b> plastifiez la feuille. Coloriez au feutre effaçable la part du cadran qui correspond à la durée, puis effacez une part à chaque fois que le temps avance. Le minuteur ne remplace pas la parole : on annonce aussi « encore deux minutes ».'),
      `<div class="grille g2">${[[5, 5, 1], [10, 10, 1], [15, 3, 5], [30, 6, 5]].map(([m, n, part]) => `<div class="cadre" style="display:flex;flex-direction:column;align-items:center;gap:3mm;min-height:95mm"><div class="etiquette">${m} minutes</div><svg viewBox="0 0 100 100" width="62mm" height="62mm"><circle cx="50" cy="50" r="46" fill="#fff" stroke="#1e2746" stroke-width="2"/>${Array.from({ length: n }, (_, i) => { const ang = (i / n) * 2 * Math.PI - Math.PI / 2; return `<line x1="50" y1="50" x2="${(50 + 46 * Math.cos(ang)).toFixed(1)}" y2="${(50 + 46 * Math.sin(ang)).toFixed(1)}" stroke="#9aa1b4" stroke-width="1"/>`; }).join('')}<circle cx="50" cy="50" r="3" fill="#5146d8"/></svg><div style="font-size:8pt">Une part = ${part} minute${part > 1 ? 's' : ''}</div></div>`).join('')}</div>`,
    ],
  },
];
